package com.iss.itreasury.loan.integratedCredit.customerfeedback.dataentity;

import java.sql.Timestamp;
import java.util.Date;

import com.iss.itreasury.util.ITreasuryBaseDataEntity;

/**
 * * Created 2008-6-16 14:50:59
 * 
 * @author wxsu LoanAccountreceivableinfo generated by MyEclipse - Hibernate
 *         Tools
 */

public class LoanAccountreceivableinfo extends ITreasuryBaseDataEntity
		implements java.io.Serializable {

	// Fields

	private long id;

	private long gageid;

	private long debtor;

	private String contractorinvoicenumber;

	private double accountreceivableamount;

	private double accountreceivablebalance;

	private Timestamp returntime;

	private String accountname;

	private String accountnumber;

	private String operbank;

	private long transfernotice;

	private long accountreceivablepromises;

	private long officeid;

	private long currency;

	private long inputuserid;

	private Timestamp inputdate;

	private long status;

	// Constructors

	/** default constructor */
	public LoanAccountreceivableinfo() {
	}

	/** minimal constructor */
	public LoanAccountreceivableinfo(long id) {
		this.id = id;
	}

	/** full constructor */
	public LoanAccountreceivableinfo(long id, long gageid, long debtor,
			String contractorinvoicenumber, double accountreceivableamount,
			double accountreceivablebalance, Timestamp returntime,
			String accountname, String accountnumber, String operbank,
			long transfernotice, long accountreceivablepromises, long officeid,
			long currency, long inputuserid, Timestamp inputdate, long status) {
		this.id = id;
		this.gageid = gageid;
		this.debtor = debtor;
		this.contractorinvoicenumber = contractorinvoicenumber;
		this.accountreceivableamount = accountreceivableamount;
		this.accountreceivablebalance = accountreceivablebalance;
		this.returntime = returntime;
		this.accountname = accountname;
		this.accountnumber = accountnumber;
		this.operbank = operbank;
		this.transfernotice = transfernotice;
		this.accountreceivablepromises = accountreceivablepromises;
		this.officeid = officeid;
		this.currency = currency;
		this.inputuserid = inputuserid;
		this.inputdate = inputdate;
		this.status = status;
	}

	// Property accessors

	public long getGageid() {
		return this.gageid;
	}

	public void setGageid(long gageid) {
		this.gageid = gageid;
	}

	public long getDebtor() {
		return this.debtor;
	}

	public void setDebtor(long debtor) {
		this.debtor = debtor;
	}

	public String getContractorinvoicenumber() {
		return this.contractorinvoicenumber;
	}

	public void setContractorinvoicenumber(String contractorinvoicenumber) {
		this.contractorinvoicenumber = contractorinvoicenumber;
	}

	public double getAccountreceivableamount() {
		return this.accountreceivableamount;
	}

	public void setAccountreceivableamount(double accountreceivableamount) {
		this.accountreceivableamount = accountreceivableamount;
	}

	public double getAccountreceivablebalance() {
		return this.accountreceivablebalance;
	}

	public void setAccountreceivablebalance(double accountreceivablebalance) {
		this.accountreceivablebalance = accountreceivablebalance;
	}

	public Date getReturntime() {
		return this.returntime;
	}

	public void setReturntime(Timestamp returntime) {
		this.returntime = returntime;
	}

	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	public String getAccountnumber() {
		return this.accountnumber;
	}

	public void setAccountnumber(String accountnumber) {
		this.accountnumber = accountnumber;
	}

	public String getOperbank() {
		return this.operbank;
	}

	public void setOperbank(String operbank) {
		this.operbank = operbank;
	}

	public long getTransfernotice() {
		return this.transfernotice;
	}

	public void setTransfernotice(long transfernotice) {
		this.transfernotice = transfernotice;
	}

	public long getAccountreceivablepromises() {
		return this.accountreceivablepromises;
	}

	public void setAccountreceivablepromises(long accountreceivablepromises) {
		this.accountreceivablepromises = accountreceivablepromises;
	}

	public long getOfficeid() {
		return this.officeid;
	}

	public void setOfficeid(long officeid) {
		this.officeid = officeid;
	}

	public long getCurrency() {
		return this.currency;
	}

	public void setCurrency(long currency) {
		this.currency = currency;
	}

	public long getInputuserid() {
		return this.inputuserid;
	}

	public void setInputuserid(long inputuserid) {
		this.inputuserid = inputuserid;
	}

	public Date getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(Timestamp inputdate) {
		this.inputdate = inputdate;
	}

	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	public void setId(long id) {
		// TODO Auto-generated method stub

	}

	public long getId() {
		// TODO Auto-generated method stub
		return 0;
	}

}