/* Generated by Together */

package com.iss.itreasury.clientmanage.systemset.customfield.dataentity;

import java.sql.Timestamp;

import com.iss.itreasury.clientmanage.dao.CimsBaseDao;
import com.iss.itreasury.clientmanage.dataentity.CimsBaseDataEntity;
import com.iss.itreasury.util.ITreasuryBaseDataEntity;
/**
*用户自定义字段dataEntity，对应于表Client_CustomFieldSetting
* */
public class CustomFieldInfo extends CimsBaseDataEntity {
	
	/**
	 * @return Returns the fieldID.
	 */
	public long getFieldID() {
		return fieldID;
	}
	/**
	 * @param fieldID The fieldID to set.
	 */
	public void setFieldID(long fieldID) {
		putUsedField("fieldID", fieldID);
		this.fieldID = fieldID;
	}
	/**
	 * @return Returns the inputDate.
	 */
	public Timestamp getInputDate() {
		return inputDate;
	}
	/**
	 * @param inputDate The inputDate to set.
	 */
	public void setInputDate(Timestamp inputDate) {
		putUsedField("inputDate", inputDate);
		this.inputDate = inputDate;
	}
	/**
	 * @return Returns the inputUserID.
	 */
	public long getInputUserID() {
		return inputUserID;
	}
	/**
	 * @param inputUserID The inputUserID to set.
	 */
	public void setInputUserID(long inputUserID) {
		putUsedField("inputUserID", inputUserID);
		this.inputUserID = inputUserID;
	}
	/**
	 * @return Returns the name.
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name The name to set.
	 */
	public void setName(String name) {
		putUsedField("name", name);
		this.name = name;
	}
	/**
	 * @return Returns the statusID.
	 */
	public long getStatusID() {
		return statusID;
	}
	/**
	 * @param statusID The statusID to set.
	 */
	public void setStatusID(long statusID) {
		putUsedField("statusID", statusID);
		this.statusID = statusID;
	}
	private long fieldID = -1;
	private String name = "";
	private long inputUserID = -1;             //录入人
	private Timestamp inputDate = null; 		//录入时间
	private long statusID = 1;            //设置状态
	
	private long officeID = -1;
	private long currencyID = -1;
	

	public long getCurrencyID() {
		return currencyID;
	}
	public void setCurrencyID(long currencyID) {
		putUsedField("currencyID", currencyID);
		this.currencyID = currencyID;
	}
	public long getOfficeID()
	{
		return officeID;
	}
	public void setOfficeID(long officeID)
	{
		putUsedField("officeID", officeID);
		this.officeID = officeID;
	}
	

}
