/* Generated by Together */

package com.iss.itreasury.bill.bizdelegation;

import com.iss.itreasury.bill.query.bizlogic.QueryOperation;
import com.iss.itreasury.bill.query.dataentity.*;
import com.iss.system.dao.PageLoader;

public class QueryDelegation {

	private QueryOperation facade = null;
    
	public QueryDelegation()
	{
		facade = new QueryOperation();
	}

	public String getOrderSQL(String orderParamString, long desc)
	{
		return facade.getOrderSQL(orderParamString,desc);
	}
	
	public PageLoader queryBillType(QueryBillTypeInfo qInfo) throws Exception
	{
		return facade.queryBillType(qInfo);
	}
	
	public PageLoader queryBlankVoucher(QueryBlankVoucherInfo qInfo) throws Exception
	{
		return facade.queryBlankVoucher(qInfo);
	}
	
	public PageLoader queryBill(QueryBillInfo qInfo) throws Exception
	{
		return facade.queryBill(qInfo);
	}
	
	public PageLoader queryBill1(QueryBillInfo qInfo) throws Exception
	{
		return facade.queryBill1(qInfo);
	}
	public double queryBill1_SumAmount(QueryBillInfo qInfo)throws Exception{
		return facade.queryBill1_SumAmount(qInfo);
	}
	public PageLoader queryBlackList(QueryBlackListInfo qInfo) throws Exception
	{
		return facade.queryBlackList(qInfo);
	}
	
	public PageLoader queryBlankTransaction(QueryBlankTransactionInfo qInfo) throws Exception
	{
		return facade.queryBlankTransaction(qInfo);
	}
	
	public PageLoader queryDraftTransaction(QueryDraftTransactionInfo qInfo) throws Exception
	{
		return facade.queryDraftTransaction(qInfo);
	}
	public PageLoader queryBlankVoucherTracing(QueryTracingInfo qInfo) throws Exception
	{
		return facade.queryBlankVoucherTracing(qInfo);
	}

	public PageLoader queryBillTracing(QueryTracingInfo qInfo) throws Exception
	{
		return facade.queryBillTracing(qInfo);
	}
	
}
