/*
 * Created on 2004-6-14
 *
 * To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package com.iss.itreasury.securities.mywork.dataentity;

import com.iss.itreasury.securities.mywork.dao.SEC_MyWorkDAO;
import com.iss.itreasury.securities.util.SECConstant;

/**
 * @author lgwang
 *
 * To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
public class TransactionType {
	public static long[] getTransactionTypeCode(long BusinessType){
		long[] transactionType = null;
		
		if (BusinessType == SEC_MyWorkDAO.SEC_APPLYFORM){
			transactionType = new long[117];
			transactionType[0] = SECConstant.BusinessType.CAPITAL_IN_CREDIT_EXTENSION.CAPITAL_IN_CREDIT_EXTENSION ;
			transactionType[1] = SECConstant.BusinessType.CAPITAL_OUT_CREDIT_EXTENSION.CAPITAL_OUT_CREDIT_EXTENSION ;
			transactionType[2] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_IN ;
			transactionType[3] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_IN_REPAY ;
			transactionType[4] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_OUT ;
			transactionType[5] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_OUT_REPAY ;
			transactionType[6] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_ONLINE ;
			transactionType[7] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_REPAY ;
			transactionType[8] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_WIN ;
			transactionType[9] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_ONLINE ;
			transactionType[10] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_REPAY ;
			transactionType[11] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_WIN ;
			transactionType[12] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_BID ;
			transactionType[13] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_MARGIN_REPAY ;
			transactionType[14] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_MARGIN_SUPPLY ;
			transactionType[15] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_QUOTA_CONFIRM ;
			transactionType[16] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID ;
			transactionType[17] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_MARGIN_REPAY ;
			transactionType[18] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_MARGIN_SUPPLY ;
			transactionType[19] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_QUOTA_CONFIRM ;
			transactionType[20] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_BUYIN ;
			transactionType[21] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_MELON_CUTTING ;
			transactionType[22] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_RATION ;
			transactionType[23] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_RATION_ONLINE ;
			transactionType[24] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_SELL ;
			transactionType[25] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_TAKEBACK ;
			transactionType[26] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_BID.NOTE_BID ;
			transactionType[27] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_ACCRUAL_IN ;
			transactionType[28] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_BUYIN ;
			transactionType[29] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_MATURITY_REPAY ;
			transactionType[30] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_SELL ;
			transactionType[31] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.BOND_REPAY ;
			transactionType[32] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.BOND_REPURCHASE ;
			transactionType[33] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.FUND_REPAY ;
			transactionType[34] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.FUND_REPURCHASE ;
			transactionType[35] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.BOND_REPAY ;
			transactionType[36] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.BOND_REPURCHASE ;
			transactionType[37] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.FUND_REPAY ;
			transactionType[38] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.FUND_REPURCHASE ;
			transactionType[39] = SECConstant.BusinessType.BANK_NATIONAL_BOND_BID.BOND_BID ;
			transactionType[40] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[41] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[42] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[43] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[44] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_BID.BOND_BID ;
			transactionType[45] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[46] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[47] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[48] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[49] = SECConstant.BusinessType.FINANCIAL_BOND_BID.BOND_BID ;
			transactionType[50] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[51] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[52] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[53] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[54] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_BID.BOND_BID ;
			transactionType[55] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[56] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[57] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[58] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[59] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID ;
			transactionType[60] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_MARGIN_REPAY ;
			transactionType[61] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_MARGIN_SUPPLY ;
			transactionType[62] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_QUOTA_CONFIRM ;
			transactionType[63] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[64] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[65] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[66] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_SELL ;
			transactionType[67] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_ONLINE ;
			transactionType[68] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_REPAY ;
			transactionType[69] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_WIN ;
			transactionType[70] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID ;
			transactionType[71] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_MARGIN_REPAY ;
			transactionType[72] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_MARGIN_SUPPAY ;
			transactionType[73] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_QUOTA_CONFIRM ;
			transactionType[74] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[75] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[76] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[77] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_SELL ;
			transactionType[78] = SECConstant.BusinessType.DEBT_TO_EQUITY.DEBT_TO_EQUITY ;
			transactionType[79] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_ONLINE ;
			transactionType[80] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_REPAY ;
			transactionType[81] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_WIN ;
			transactionType[82] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID ;
			transactionType[83] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_MARGIN_REPAY ;
			transactionType[84] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_MARGIN_SUPPLY ;
			transactionType[85] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_QUOTA_CONFIRM ;
			transactionType[86] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_BUYIN ;
			transactionType[87] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_MATURITY_SETTLE ;
			transactionType[88] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_MELON_CUTTING ;
			transactionType[89] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_SELL ;
			transactionType[90] = SECConstant.BusinessType.MUTUAL_FUND_SUBSCRIBE.FUND_SUBSCRIBE ;
			transactionType[91] = SECConstant.BusinessType.MUTUAL_FUND_SUBSCRIBE.FUND_SUBSCRIBE_CONFIRM ;
			transactionType[92] = SECConstant.BusinessType.MUTUAL_FUND_BID.FUND_BID ;
			transactionType[93] = SECConstant.BusinessType.MUTUAL_FUND_BID.FUND_BID_CONFIRM ;
			transactionType[94] = SECConstant.BusinessType.MUTUAL_FUND_REDEEM.FUND_REDEEM ;
			transactionType[95] = SECConstant.BusinessType.MUTUAL_FUND_MELON_CUTTING.FUND_CASH_MELON_CUTTING ;
			transactionType[96] = SECConstant.BusinessType.MUTUAL_FUND_MELON_CUTTING.FUND_SHARE_MELON_CUTTING ;
			transactionType[97] = SECConstant.BusinessType.CAPITAL_REPURCHASE.CAPITAL_REPURCHASE ;
			transactionType[98] = SECConstant.BusinessType.CAPITAL_REPURCHASE.INTEREST_PAYMENT ;
			transactionType[99] = SECConstant.BusinessType.CAPITAL_REPURCHASE.PAYBACK_NOTIFY ;
			transactionType[100] = SECConstant.BusinessType.CAPITAL_REPURCHASE.REPURCHASE_NOTIFY ;
			transactionType[101] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[102] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[103] = SECConstant.BusinessType.ENTRUST_FINANCING.ENTRUST_FINANCING ;
			transactionType[104] = SECConstant.BusinessType.ENTRUST_FINANCING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[105] = SECConstant.BusinessType.ENTRUSTED_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[106] = SECConstant.BusinessType.ENTRUSTED_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[107] = SECConstant.BusinessType.ENTRUSTED_FINANCING.ENTRUSTED_FINANCING ;
			transactionType[108] = SECConstant.BusinessType.ENTRUSTED_FINANCING.INCOME_PAYMENT_NOTIFY ;
			transactionType[109] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.FOREIGN_CURRENCY_INVESTMENT ;
			transactionType[110] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INCOME_DRAWBACK_NOTIFY ;
			transactionType[111] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_DRAWBACK_NOTIFY ;
			transactionType[112] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_PAYMENT_NOTIFY ;
			transactionType[113] = SECConstant.BusinessType.BOND_UNDERWRITING.BOND_UNDERWRITING ;
			transactionType[114] = SECConstant.BusinessType.BOND_UNDERWRITING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[115] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_DRAWBACK_NOTIFY ;
			transactionType[116] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_PAYMENT_NOTIFY ;
		}
		else if(BusinessType == SEC_MyWorkDAO.SEC_NOTICE){
			transactionType = new long[121];
			transactionType[0] = SECConstant.BusinessType.CAPITAL_IN_CREDIT_EXTENSION.CAPITAL_IN_CREDIT_EXTENSION ;
			transactionType[1] = SECConstant.BusinessType.CAPITAL_OUT_CREDIT_EXTENSION.CAPITAL_OUT_CREDIT_EXTENSION ;
			transactionType[2] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_IN ;
			transactionType[3] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_IN_REPAY ;
			transactionType[4] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_OUT ;
			transactionType[5] = SECConstant.BusinessType.CAPITAL_LANDING.CAPITAL_OUT_REPAY ;
			transactionType[6] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_ONLINE ;
			transactionType[7] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_REPAY ;
			transactionType[8] = SECConstant.BusinessType.STOCK_BID_ONLINE.INITIAL_OFFERING_BID_WIN ;
			transactionType[9] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_ONLINE ;
			transactionType[10] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_REPAY ;
			transactionType[11] = SECConstant.BusinessType.STOCK_BID_ONLINE.PROMOTION_BID_WIN ;
			transactionType[12] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_BID ;
			transactionType[13] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_MARGIN_REPAY ;
			transactionType[14] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_MARGIN_SUPPLY ;
			transactionType[15] = SECConstant.BusinessType.STOCK_BID.INITIAL_OFFERING_QUOTA_CONFIRM ;
			transactionType[16] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID ;
			transactionType[17] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_MARGIN_REPAY ;
			transactionType[18] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_MARGIN_SUPPLY ;
			transactionType[19] = SECConstant.BusinessType.STOCK_BID.PROMOTION_BID_QUOTA_CONFIRM ;
			transactionType[20] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_BUYIN ;
			transactionType[21] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_MELON_CUTTING ;
			transactionType[22] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_RATION ;
			transactionType[23] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_RATION_ONLINE ;
			transactionType[24] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_SELL ;
			transactionType[25] = SECConstant.BusinessType.STOCK_TRANSACTION.STOCK_TAKEBACK ;
			transactionType[26] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_BID.NOTE_BID ;
			transactionType[27] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_ACCRUAL_IN ;
			transactionType[28] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_BUYIN ;
			transactionType[29] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_MATURITY_REPAY ;
			transactionType[30] = SECConstant.BusinessType.CENTRAL_BANK_NOTE_TRANSACTION.NOTE_SELL ;
			transactionType[31] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.BOND_REPAY ;
			transactionType[32] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.BOND_REPURCHASE ;
			transactionType[33] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.FUND_REPAY ;
			transactionType[34] = SECConstant.BusinessType.BANK_BOND_REPURCHASE.FUND_REPURCHASE ;
			transactionType[35] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.BOND_REPAY ;
			transactionType[36] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.BOND_REPURCHASE ;
			transactionType[37] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.FUND_REPAY ;
			transactionType[38] = SECConstant.BusinessType.EXCHANGECENTER_BOND_REPURCHASE.FUND_REPURCHASE ;
			transactionType[39] = SECConstant.BusinessType.BANK_NATIONAL_BOND_BID.BOND_BID ;
			transactionType[40] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[41] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[42] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[43] = SECConstant.BusinessType.BANK_NATIONAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[44] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_BID.BOND_BID ;
			transactionType[45] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[46] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[47] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[48] = SECConstant.BusinessType.EXCHANGECENTER_NATIONAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[49] = SECConstant.BusinessType.FINANCIAL_BOND_BID.BOND_BID ;
			transactionType[50] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[51] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[52] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[53] = SECConstant.BusinessType.FINANCIAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[54] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_BID.BOND_BID ;
			transactionType[55] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[56] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[57] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[58] = SECConstant.BusinessType.POLICY_RELATED_FINANCIAL_BOND_TRANSACTION.BOND_SELL ;
			transactionType[59] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID ;
			transactionType[60] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_MARGIN_REPAY ;
			transactionType[61] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_MARGIN_SUPPLY ;
			transactionType[62] = SECConstant.BusinessType.ENTERPRISE_BOND_BID.BOND_BID_QUOTA_CONFIRM ;
			transactionType[63] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[64] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[65] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[66] = SECConstant.BusinessType.ENTERPRISE_BOND_TRANSACTION.BOND_SELL ;
			transactionType[67] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_ONLINE ;
			transactionType[68] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_REPAY ;
			transactionType[69] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID_ONLINE.BOND_BID_WIN ;
			transactionType[70] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID ;
			transactionType[71] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_MARGIN_REPAY ;
			transactionType[72] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_MARGIN_SUPPAY ;
			transactionType[73] = SECConstant.BusinessType.TRANSFORMABLE_BOND_BID.BOND_BID_QUOTA_CONFIRM ;
			transactionType[74] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_ACCRUAL_IN ;
			transactionType[75] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_BUYIN ;
			transactionType[76] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_MATURITY_REPAY ;
			transactionType[77] = SECConstant.BusinessType.TRANSFORMABLE_BOND_TRANSACTION.BOND_SELL ;
			transactionType[78] = SECConstant.BusinessType.DEBT_TO_EQUITY.DEBT_TO_EQUITY ;
			transactionType[79] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_ONLINE ;
			transactionType[80] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_REPAY ;
			transactionType[81] = SECConstant.BusinessType.ENCLOSED_FUND_BID_ONLINE.FUND_BID_WIN ;
			transactionType[82] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID ;
			transactionType[83] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_MARGIN_REPAY ;
			transactionType[84] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_MARGIN_SUPPLY ;
			transactionType[85] = SECConstant.BusinessType.ENCLOSED_FUND_BID.FUND_BID_QUOTA_CONFIRM ;
			transactionType[86] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_BUYIN ;
			transactionType[87] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_MATURITY_SETTLE ;
			transactionType[88] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_MELON_CUTTING ;
			transactionType[89] = SECConstant.BusinessType.ENCLOSED_FUND_TRANSACTION.FUND_SELL ;
			transactionType[90] = SECConstant.BusinessType.MUTUAL_FUND_SUBSCRIBE.FUND_SUBSCRIBE ;
			transactionType[91] = SECConstant.BusinessType.MUTUAL_FUND_SUBSCRIBE.FUND_SUBSCRIBE_CONFIRM ;
			transactionType[92] = SECConstant.BusinessType.MUTUAL_FUND_BID.FUND_BID ;
			transactionType[93] = SECConstant.BusinessType.MUTUAL_FUND_BID.FUND_BID_CONFIRM ;
			transactionType[94] = SECConstant.BusinessType.MUTUAL_FUND_REDEEM.FUND_REDEEM ;
			transactionType[95] = SECConstant.BusinessType.MUTUAL_FUND_MELON_CUTTING.FUND_CASH_MELON_CUTTING ;
			transactionType[96] = SECConstant.BusinessType.MUTUAL_FUND_MELON_CUTTING.FUND_SHARE_MELON_CUTTING ;
			transactionType[97] = SECConstant.BusinessType.CAPITAL_REPURCHASE.CAPITAL_REPURCHASE ;
			transactionType[98] = SECConstant.BusinessType.CAPITAL_REPURCHASE.INTEREST_PAYMENT ;
			transactionType[99] = SECConstant.BusinessType.CAPITAL_REPURCHASE.PAYBACK_NOTIFY ;
			transactionType[100] = SECConstant.BusinessType.CAPITAL_REPURCHASE.REPURCHASE_NOTIFY ;
			transactionType[101] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[102] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[103] = SECConstant.BusinessType.ENTRUST_FINANCING.ENTRUST_FINANCING ;
			transactionType[104] = SECConstant.BusinessType.ENTRUST_FINANCING.SECURITIES_PAYMENT_NOTIFY ;
			transactionType[105] = SECConstant.BusinessType.ENTRUST_FINANCING.SECURITIES_DRAWBACK_NOTIFY ;
			transactionType[106] = SECConstant.BusinessType.ENTRUST_FINANCING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[107] = SECConstant.BusinessType.ENTRUSTED_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[108] = SECConstant.BusinessType.ENTRUSTED_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[109] = SECConstant.BusinessType.ENTRUSTED_FINANCING.ENTRUSTED_FINANCING ;
			transactionType[110] = SECConstant.BusinessType.ENTRUSTED_FINANCING.INCOME_PAYMENT_NOTIFY ;
			transactionType[111] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.FOREIGN_CURRENCY_INVESTMENT ;
			transactionType[112] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INCOME_DRAWBACK_NOTIFY ;
			transactionType[113] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_DRAWBACK_NOTIFY ;
			transactionType[114] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_PAYMENT_NOTIFY ;
			transactionType[115] = SECConstant.BusinessType.BOND_UNDERWRITING.BOND_UNDERWRITING ;
			transactionType[116] = SECConstant.BusinessType.BOND_UNDERWRITING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[117] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_DRAWBACK_NOTIFY ;
			transactionType[118] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_PAYMENT_NOTIFY ;
			//-------------
			transactionType[119] = SECConstant.BusinessType.CAPITAL_TRANSFER.CAPITAL_IN ;
			transactionType[120] = SECConstant.BusinessType.CAPITAL_TRANSFER.CAPITAL_OUT ;
		}
		else if(BusinessType == SEC_MyWorkDAO.SEC_CONTRACT){
			transactionType = new long[15];
			transactionType[0] = SECConstant.BusinessType.CAPITAL_REPURCHASE.CAPITAL_REPURCHASE ;
			transactionType[1] = SECConstant.BusinessType.CAPITAL_REPURCHASE.INTEREST_PAYMENT ;
			transactionType[2] = SECConstant.BusinessType.CAPITAL_REPURCHASE.PAYBACK_NOTIFY ;
			transactionType[3] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[4] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[5] = SECConstant.BusinessType.ENTRUST_FINANCING.ENTRUST_FINANCING ;
			transactionType[6] = SECConstant.BusinessType.ENTRUST_FINANCING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[7] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.FOREIGN_CURRENCY_INVESTMENT ;
			transactionType[8] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INCOME_DRAWBACK_NOTIFY ;
			transactionType[9] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_DRAWBACK_NOTIFY ;
			transactionType[10] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_PAYMENT_NOTIFY ;
			transactionType[11] = SECConstant.BusinessType.BOND_UNDERWRITING.BOND_UNDERWRITING ;
			transactionType[12] = SECConstant.BusinessType.BOND_UNDERWRITING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[13] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_DRAWBACK_NOTIFY ;
			transactionType[14] = SECConstant.BusinessType.BOND_UNDERWRITING.UNDERWRITING_PAYMENT_NOTIFY ;
		}
		else if(BusinessType == SEC_MyWorkDAO.SEC_PLAN){
			transactionType = new long[8];
			transactionType[0] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_DRAWBACK_NOTIFY ;
			transactionType[1] = SECConstant.BusinessType.ENTRUST_FINANCING.CORPORACITY_PAYMENT_NOTIFY ;
			transactionType[2] = SECConstant.BusinessType.ENTRUST_FINANCING.ENTRUST_FINANCING ;
			transactionType[3] = SECConstant.BusinessType.ENTRUST_FINANCING.INCOME_DRAWBACK_NOTIFY ;
			transactionType[4] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.FOREIGN_CURRENCY_INVESTMENT ;
			transactionType[5] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INCOME_DRAWBACK_NOTIFY ;
			transactionType[6] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_DRAWBACK_NOTIFY ;
			transactionType[7] = SECConstant.BusinessType.FOREIGN_CURRENCY_INVESTMENT.INVESTMENT_PAYMENT_NOTIFY ;
		}
		
		return transactionType;
	}
}
