/* Generated by Together */

package com.iss.itreasury.codingrule.tags;

/* Author:YanLiu */

import java.io.IOException;
import java.util.Collection;
import java.util.Iterator;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.tagext.TagSupport;

import com.iss.itreasury.codingrule.dataentity.CodingSectInfo;
import com.iss.itreasury.codingrule.util.RuleEnv;

//根据RuleEnv解析出的xml内容,生成编码段select控件
public class CodingSectTag extends TagSupport 
{
	private String controlName = "codingSect"; 		//控件名称
	private long defaultValue = -1;					//默认值		
	private boolean isDisabled = false;				//是否disable
	private String onchange = "";					//onchange方法
	private String extProperty = "";				//扩展属性
	
    public int doStartTag() throws JspException 
    {
    	try 
    	{
			JspWriter out = pageContext.getOut();		
			String strOutPrint = "";
			
			RuleEnv env = RuleEnv.getInstance();
			Collection c_CodingSect = null;
			if(env.getCodingSects()!=null)
				c_CodingSect = env.getCodingSects().values();
			
			strOutPrint = "<select class=\"select\" name=\"" + controlName + "\" "+ extProperty ;
			if(isDisabled)
			{
				strOutPrint +=" disabled ";
			}
			if(onchange != null)
			{
				strOutPrint +=" onchange=\" "+onchange+"\" ";
			}	
			strOutPrint += ">\n";
				
			if(c_CodingSect!=null && c_CodingSect.size()>0)
			{
				Iterator it = c_CodingSect.iterator();	
				while(it.hasNext())
				{
					CodingSectInfo info = (CodingSectInfo)it.next();
					
					strOutPrint += "<option value='"+info.getId()+"' ";
					if(info.getId() == defaultValue)
					{
						strOutPrint += " selected ";
					}	
					strOutPrint += " > ";
					strOutPrint += info.getDesc();
					strOutPrint += " </option> \n";					
				}	
			}	
			strOutPrint += "</select>\n";
			
			out.println(strOutPrint);			
		} 
    	catch (IOException ex) 
    	{
		}
		catch (Exception ex) 
		{
		}
        return SKIP_BODY;
    }

    public int doEndTag() throws JspException {
        //
        // Write your code here
        //
        return EVAL_PAGE;
    }

	public String getControlName() {
		return controlName;
	}

	public void setControlName(String controlName) {
		this.controlName = controlName;
	}

	public long getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(long defaultValue) {
		this.defaultValue = defaultValue;
	}

	public String getExtProperty() {
		return extProperty;
	}

	public void setExtProperty(String extProperty) {
		this.extProperty = extProperty;
	}

	public boolean isDisabled() {
		return isDisabled;
	}

	public void setDisabled(boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	public String getOnchange() {
		return onchange;
	}

	public void setOnchange(String onchange) {
		this.onchange = onchange;
	}
}
