package com.iss.itreasury.ebank.obfinanceinstr.bizlogic;

import com.iss.itreasury.ebank.obfinanceinstr.dataentity.*;
import com.iss.itreasury.ebank.util.SessionOB;
import com.iss.itreasury.util.IRollbackException;

import javax.ejb.EJBObject;
import javax.servlet.ServletRequest;

import java.rmi.*;
import java.sql.Timestamp;
import java.util.Collection;

/**
 * Created 2002-12-7 19:29:33
 * Code generated by the Forte for Java EJB Module
 * @author Wang Yi
 */

public interface OBFinanceInstr extends EJBObject
{ 
	public long addTrans(FinanceInfo info) throws RemoteException,Exception ;
	public long checkCapitalTrans(FinanceInfo info) throws RemoteException, Exception;
	public long addCapitalTrans(FinanceInfo info) throws RemoteException,Exception ;
	public long updateCapitalTrans(FinanceInfo info) throws RemoteException,Exception;
	public long deleteCapitalTrans(FinanceInfo info) throws RemoteException,Exception;   
	public long check(long lInstructionID, long lCheckUserID,long lCurrencyID) throws RemoteException,Exception;
	public long billcheck(long lInstructionID, long lCheckUserID,long lCurrencyID,String billcheckabstract,boolean cancelCheck,Timestamp dtmodify) throws RemoteException,Exception;
	public long cancelCheck(long lInstructionID, long lCheckUserID) throws RemoteException,Exception;
	public long sign(FinanceInfo info) throws RemoteException,Exception;
	public long cancelSign(long lInstructionID, long lSignUserID) throws RemoteException,Exception;
	public OBBankPayInfo findByID (long lInstructionID) throws  RemoteException, Exception;
	public FinanceInfo findByID(long lInstructionID, long lUserID, long lCurrencyID) throws RemoteException,Exception;
	public FinanceInfo findByIDForSett(long lInstructionID, long lClientID, long lCurrencyID) throws RemoteException,Exception;
	public SubLoanAccountDetailInfo findSubLoanAccountDetailByCondition(SubLoanAccountDetailInfo subLoanAccountDetailInfo) throws RemoteException,Exception;
	public PayerOrPayeeInfo getLoanAccountInfo(long lclientID,long lcurrencyID,long laccountType)throws RemoteException,Exception;
	public FinanceInfo getFinanceInfo(long id)throws RemoteException,Exception;
	public Collection getTransOpenFixdDePosit(FinanceInfo financeInfo)throws RemoteException,Exception;
	public long TransOpenFixdDePositUpdtae(FinanceInfo financeInfo) throws RemoteException, Exception;
	public Collection isTransOpenFixdDePosit(FinanceInfo financeInfo) throws RemoteException, Exception;
	public long doApproval(FinanceInfo financeInfo) throws RemoteException, Exception;
	public long doApproval(OBBankPayInfo obBankPayInfo ) throws RemoteException, Exception;
	public long cancelApproval(FinanceInfo financeInfo)throws RemoteException, IRollbackException,Exception;
	public long cancelApproval(OBBankPayInfo obBankPayInfo)throws RemoteException, IRollbackException,Exception;
	public long check(FinanceInfo financeInfo) throws RemoteException, IRollbackException,Exception;
	public long cancelCheck(FinanceInfo financeInfo) throws RemoteException,Exception;
	public long billcheck(FinanceInfo financeInfo,boolean cancelCheck) throws RemoteException,IRollbackException;
	public long matching (OBBankPayInfo info,long userId)throws  RemoteException, Exception;
	public Collection query (QueryCapForm info) throws  RemoteException, Exception;
	public long addBankPay(OBBankPayInfo info) throws  RemoteException, Exception;
	public long checkBankPay(long lInstructionID,long lCheckUserID) throws  RemoteException, Exception;
	public long cancelCheckBankPay(long lInstructionID, long lCheckUserID) throws  RemoteException, Exception;
	public long signBankPay(long lInstructionID, long lSignUserID) throws  RemoteException, Exception;
	public long AuditingBankPay(long lInstructionID, long lSignUserID) throws  RemoteException, Exception;
	public long cancelSignBankPay(long lInstructionID, long lSignUserID) throws  RemoteException, Exception;
	public long cancelAuditingBankPay(long lInstructionID, long lSignUserID) throws  RemoteException, Exception;
	public boolean addBatchCapitalTrans(FinanceInfo[] financeInfoArray,SessionOB sessionMng,String remoteAddr,String remoteHost)throws RemoteException,Exception;
	
	
}
