package com.iss.itreasury.integratedCredit.dataentity;

// default package



/**
 * wxsu 2008-06-17 22:06
 * 经营分析属性清单
 * LoanManageanalyse generated by MyEclipse - Hibernate Tools
 */

public class LoanManageanalyse  implements java.io.Serializable {


    // Fields    

     private long id;
     private long creditgradeid;
     private long officeid;
     private long currencyid;
     private String incomeform;
     private String competecondition;
     private String marketlocation;
     private String elementarycondition;
     private String ambienceanalyse;
     private String advanced;
     private String startrate;
     private String managestandard;
     private String consist;
     private String completecondition;
     private String situation;
     private String designcondition;
     private String planning;
     private long status;


    // Constructors

    /** default constructor */
    public LoanManageanalyse() {
    }

	/** minimal constructor */
    public LoanManageanalyse(long id) {
        this.id = id;
    }
    
    /** full constructor */
    public LoanManageanalyse(long id, long creditgradeid, long officeid, long currencyid, String incomeform, String competecondition, String marketlocation, String elementarycondition, String ambienceanalyse, String advanced, String startrate, String managestandard, String consist, String completecondition, String situation, String designcondition, String planning, long status) {
        this.id = id;
        this.creditgradeid = creditgradeid;
        this.officeid = officeid;
        this.currencyid = currencyid;
        this.incomeform = incomeform;
        this.competecondition = competecondition;
        this.marketlocation = marketlocation;
        this.elementarycondition = elementarycondition;
        this.ambienceanalyse = ambienceanalyse;
        this.advanced = advanced;
        this.startrate = startrate;
        this.managestandard = managestandard;
        this.consist = consist;
        this.completecondition = completecondition;
        this.situation = situation;
        this.designcondition = designcondition;
        this.planning = planning;
        this.status = status;
    }

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public long getCreditgradeid() {
        return this.creditgradeid;
    }
    
    public void setCreditgradeid(long creditgradeid) {
        this.creditgradeid = creditgradeid;
    }

    public long getOfficeid() {
        return this.officeid;
    }
    
    public void setOfficeid(long officeid) {
        this.officeid = officeid;
    }

    public long getCurrencyid() {
        return this.currencyid;
    }
    
    public void setCurrencyid(long currencyid) {
        this.currencyid = currencyid;
    }

    public String getIncomeform() {
        return this.incomeform;
    }
    
    public void setIncomeform(String incomeform) {
        this.incomeform = incomeform;
    }

    public String getCompetecondition() {
        return this.competecondition;
    }
    
    public void setCompetecondition(String competecondition) {
        this.competecondition = competecondition;
    }

    public String getMarketlocation() {
        return this.marketlocation;
    }
    
    public void setMarketlocation(String marketlocation) {
        this.marketlocation = marketlocation;
    }

    public String getElementarycondition() {
        return this.elementarycondition;
    }
    
    public void setElementarycondition(String elementarycondition) {
        this.elementarycondition = elementarycondition;
    }

    public String getAmbienceanalyse() {
        return this.ambienceanalyse;
    }
    
    public void setAmbienceanalyse(String ambienceanalyse) {
        this.ambienceanalyse = ambienceanalyse;
    }

    public String getAdvanced() {
        return this.advanced;
    }
    
    public void setAdvanced(String advanced) {
        this.advanced = advanced;
    }

    public String getStartrate() {
        return this.startrate;
    }
    
    public void setStartrate(String startrate) {
        this.startrate = startrate;
    }

    public String getManagestandard() {
        return this.managestandard;
    }
    
    public void setManagestandard(String managestandard) {
        this.managestandard = managestandard;
    }

    public String getConsist() {
        return this.consist;
    }
    
    public void setConsist(String consist) {
        this.consist = consist;
    }

    public String getCompletecondition() {
        return this.completecondition;
    }
    
    public void setCompletecondition(String completecondition) {
        this.completecondition = completecondition;
    }

    public String getSituation() {
        return this.situation;
    }
    
    public void setSituation(String situation) {
        this.situation = situation;
    }

    public String getDesigncondition() {
        return this.designcondition;
    }
    
    public void setDesigncondition(String designcondition) {
        this.designcondition = designcondition;
    }

    public String getPlanning() {
        return this.planning;
    }
    
    public void setPlanning(String planning) {
        this.planning = planning;
    }

    public long getStatus() {
        return this.status;
    }
    
    public void setStatus(long status) {
        this.status = status;
    }
   








}