package com.iss.itreasury.securities.setting.bizlogic;
import javax.ejb.*;

import com.iss.itreasury.securities.exception.SecuritiesException;
import com.iss.itreasury.securities.setting.dataentity.CounterPartBankAccountInfo;
import com.iss.itreasury.securities.setting.dataentity.CounterPartInfo;

/**
 * Created 2004-3-15 15:01:53
 * Code generated by the Sun ONE Studio EJB Builder
 * @author cpf
 */


public class SettingEJB implements javax.ejb.SessionBean {
    private javax.ejb.SessionContext context;
    
    
    /**
     * @see javax.ejb.SessionBean#setSessionContext(javax.ejb.SessionContext)
     */
    public void setSessionContext(javax.ejb.SessionContext aContext) {
        context=aContext;
    }
    
    
    /**
     * @see javax.ejb.SessionBean#ejbActivate()
     */
    public void ejbActivate() {
        
    }
    
    
    /**
     * @see javax.ejb.SessionBean#ejbPassivate()
     */
    public void ejbPassivate() {
        
    }
    
    
    /**
     * @see javax.ejb.SessionBean#ejbRemove()
     */
    public void ejbRemove() {
        
    }
    
    
    /**
     * See section 7.10.3 of the EJB 2.0 specification
     */
    public void ejbCreate( ) throws javax.ejb.CreateException {
        
    }
	    
	public void saveCounterPart(CounterPartInfo counterPartInfo,CounterPartBankAccountInfo counterPartBankAccountInfo) throws java.rmi.RemoteException,SecuritiesException{
//		System.out.println("counterPartInfo.ID = " +counterPartInfo.getId());
//		System.out.println("counterPartBankAccountInfo.ID = "+ counterPartBankAccountInfo.getId());
//      CounterPartBean counterPartBean = new CounterPartBean();      
//      counterPartBean.saveCounterPart(counterPartInfo,counterPartBankAccountInfo);    
    
    }

	
	/**
	 * 返回交易对手资料
	 * @param counterPartID
	 * @return
	 * @throws java.rmi.RemoteException
	 * @throws SecuritiesException
	 */
	public CounterPartInfo findCounterPartById(long counterPartId) throws java.rmi.RemoteException, SecuritiesException
	{
//		System.out.println("lhj debug info :: SettingEJB::findCounterPartById start");
//		CounterPartBean counterPartBean = new CounterPartBean(); 		
//		System.out.println("lhj debug info :: SettingEJB::findCounterPartById end");
//		return  counterPartBean.findCounterPartById(counterPartId); 
     return null;
	} 
    
    /**
     * 返回交易对手开户行资料
     * @param counterPartBankAccountID
     * @return
     * @throws java.rmi.RemoteException
     * @throws SecuritiesException
     */
	public CounterPartBankAccountInfo findCounterPartBankAccountById(long counterPartBankAccountId) throws java.rmi.RemoteException, SecuritiesException
	{
//		System.out.println("lhj debug info :: SettingEJB::findCounterPartBankAccountByID start");
//		CounterPartBean counterPartBean = new CounterPartBean(); 		
//		System.out.println("lhj debug info :: SettingEJB::findCounterPartBankAccountByID end");
//		return  counterPartBean.findCounterPartBankAccountById(counterPartBankAccountId); 
		return null;
	}
	
	public void deleteCounterPart(long counterPartId) throws java.rmi.RemoteException, SecuritiesException
	{
//		CounterPartBean counterPartBean = new CounterPartBean(); 
//		counterPartBean.deleteCounterPart(counterPartId);
	}
}
