/* Generated by Together */

package com.iss.itreasury.codingrule.dao;

import com.iss.itreasury.codingrule.dataentity.CodingRuleInfo;
import com.iss.itreasury.dao.ITreasuryDAO;

/* Author:YanLiu */

public class Sys_CodingRuleDao extends ITreasuryDAO
{
 public Sys_CodingRuleDao()
 {
	 super("SYS_CodingRule");
 }
}
