/* Generated by Together */

package com.iss.itreasury.budget.executecontrol.dataentity;
import java.sql.Timestamp;

import com.iss.itreasury.budget.dataentity.BudgetBaseDataEntity;

public class ControlInfo  extends BudgetBaseDataEntity {

	long accountID = -1 ;  //账户
    long clientID = -1;  //客户
    long ItemID=-1;       //项目id
    double amount=0;       //金额
    Timestamp executeDate =null; //执行日期
    long CheckType = -1;   //校验类型（2 保存时校验 3 复核时校验 4不校验）
    String errMsg = "";     //返回错误信息
    long errCode=-1;        //返回错误代码
	/**
	 * @return Returns the amount.
	 */
	public double getAmount() {
		return amount;
	}
	/**
	 * @param amount The amount to set.
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}
	/**
	 * @return Returns the executeDate.
	 */
	public Timestamp getExecuteDate() {
		return executeDate;
	}
	/**
	 * @param executeDate The executeDate to set.
	 */
	public void setExecuteDate(Timestamp executeDate) {
		this.executeDate = executeDate;
	}
	
	
	/**
	 * @return Returns the lItemID.
	 */
	public long getItemID() {
		return ItemID;
	}
	/**
	 * @param itemID The lItemID to set.
	 */
	public void setItemID(long itemID) {
		ItemID = itemID;
	}
	/**
	 * @return Returns the clientID.
	 */
	public long getClientID() {
		return clientID;
	}
	/**
	 * @param clientID The clientID to set.
	 */
	public void setClientID(long clientID) {
		this.clientID = clientID;
	}
	/**
	 * @return Returns the accountID.
	 */
	public long getAccountID() {
		return accountID;
	}
	/**
	 * @param accountID The accountID to set.
	 */
	public void setAccountID(long accountID) {
		this.accountID = accountID;
	}
	/**
	 * @return Returns the errCode.
	 */
	public long getErrCode() {
		return errCode;
	}
	/**
	 * @param errCode The errCode to set.
	 */
	public void setErrCode(long errCode) {
		this.errCode = errCode;
	}
	/**
	 * @return Returns the errMsg.
	 */
	public String getErrMsg() {
		return errMsg;
	}
	/**
	 * @param errMsg The errMsg to set.
	 */
	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}
	/**
	 * @return Returns the checkType.
	 */
	public long getCheckType() {
		return CheckType;
	}
	/**
	 * @param checkType The checkType to set.
	 */
	public void setCheckType(long checkType) {
		CheckType = checkType;
	}
}
