/* Generated by Together */
package com.iss.itreasury.bill.draft.dataentity;
import java.sql.Timestamp;

import com.iss.itreasury.bill.util.BillDataEntity;
import com.iss.itreasury.util.Constant;
/**
 * @author gqzhang 
 */
public class MultiBillQueryCondition  extends BillDataEntity
{
	private Timestamp dtCreateStart = null; //出票日
	private Timestamp dtCreateEnd = null; //出票日
	private Timestamp dtEndStart = null; //到期日
	private Timestamp dtEndEnd = null; //到期日
	private Timestamp dtInDateStart = null; //买入日期
	private Timestamp dtInDateEnd = null; //买入日期
	private String sCodeStart = ""; //票据编号
	private String sCodeEnd = ""; //票据编号
	private double mAmounStart = 0.0; //票面金额
	private double mAmounEnd = 0.0; //票面金额
	private long lBillSoureID = -1; //票据来源 见常量BILLConstant.其它其它其它
	private long lBillDestinationID=-1;//票据去向 同上
	private long nOfficeID = -1; //办事处
	private long nCurrencyID = -1; //币种
	private long nModuleSourceID = -1; //票据信息来源，见常量Constant.ModuleType
	private long nDraftTypeID = -1; //汇票类型
	private String strAcceptorName = ""; //承兑人名称
	private String strCurrentHolder = ""; //当前持票人
	private long nStorageStatusID = -1; //出入入库状态，见常量BILLConstant.DraftInOrOut
	private Timestamp dtQueryStart = null; //查询日期
	private Timestamp dtQueryEnd = null; //查询日期
	private String QueryBookCode = ""; //查询书编号
	private long AgentBankID=-1;	//查询代理行ID
	private long nQueryStatusID = -1; //查复状态
	private long nConsignStatusID = -1; //托收状态
	private long nConsignTime = -1; //托收次数
	private long nInputUserID = -1; //录入人
	private Timestamp dtInputDateStart = null; //录入日期
	private Timestamp dtInputDateEnd = null; //录入日期
	
	private long OrderParam=1;				//根据什么排序
	private long Desc=Constant.PageControl.CODE_ASCORDESC_ASC;//正序还是反序
	private long pageLineCount = -1; //一页显示的行数
	private long pageNo = -1;		//页码
	private long pageCount = -1;		//页码
	private Timestamp dtConsignStart=null;//托收日期
	private Timestamp dtConsignEnd=null;//托收日期
	
	/**
	 * Returns the createEnd.
	 * @return Timestamp
	 */
	public Timestamp getCreateEnd()
	{
		return dtCreateEnd;
	}

	/**
	 * Returns the createStart.
	 * @return Timestamp
	 */
	public Timestamp getCreateStart()
	{
		return dtCreateStart;
	}

	/**
	 * Returns the endEnd.
	 * @return Timestamp
	 */
	public Timestamp getEndEnd()
	{
		return dtEndEnd;
	}

	/**
	 * Returns the endStart.
	 * @return Timestamp
	 */
	public Timestamp getEndStart()
	{
		return dtEndStart;
	}

	/**
	 * Returns the inDateEnd.
	 * @return Timestamp
	 */
	public Timestamp getInDateEnd()
	{
		return dtInDateEnd;
	}

	/**
	 * Returns the inDateStart.
	 * @return Timestamp
	 */
	public Timestamp getInDateStart()
	{
		return dtInDateStart;
	}

	/**
	 * Returns the inputDateEnd.
	 * @return Timestamp
	 */
	public Timestamp getInputDateEnd()
	{
		return dtInputDateEnd;
	}

	/**
	 * Returns the inputDateStart.
	 * @return Timestamp
	 */
	public Timestamp getInputDateStart()
	{
		return dtInputDateStart;
	}

	/**
	 * Returns the queryEnd.
	 * @return Timestamp
	 */
	public Timestamp getQueryEnd()
	{
		return dtQueryEnd;
	}

	/**
	 * Returns the queryStart.
	 * @return Timestamp
	 */
	public Timestamp getQueryStart()
	{
		return dtQueryStart;
	}

	/**
	 * Returns the billSoureID.
	 * @return long
	 */
	public long getlBillSoureID()
	{
		return lBillSoureID;
	}

	/**
	 * Returns the mAmounEnd.
	 * @return double
	 */
	public double getMAmounEnd()
	{
		return mAmounEnd;
	}

	/**
	 * Returns the mAmounStart.
	 * @return double
	 */
	public double getMAmounStart()
	{
		return mAmounStart;
	}

	/**
	 * Returns the nConsignStatusID.
	 * @return long
	 */
	public long getNConsignStatusID()
	{
		return nConsignStatusID;
	}

	/**
	 * Returns the nConsignTime.
	 * @return long
	 */
	public long getNConsignTime()
	{
		return nConsignTime;
	}

	/**
	 * Returns the nCurrencyID.
	 * @return long
	 */
	public long getNCurrencyID()
	{
		return nCurrencyID;
	}

	/**
	 * Returns the nDraftTypeID.
	 * @return long
	 */
	public long getNDraftTypeID()
	{
		return nDraftTypeID;
	}

	/**
	 * Returns the nInputUserID.
	 * @return long
	 */
	public long getNInputUserID()
	{
		return nInputUserID;
	}

	/**
	 * Returns the nModuleSourceID.
	 * @return long
	 */
	public long getNModuleSourceID()
	{
		return nModuleSourceID;
	}

	/**
	 * Returns the nOfficeID.
	 * @return long
	 */
	public long getNOfficeID()
	{
		return nOfficeID;
	}

	/**
	 * Returns the nQueryStatusID.
	 * @return long
	 */
	public long getNQueryStatusID()
	{
		return nQueryStatusID;
	}

	/**
	 * Returns the nStorageStatusID.
	 * @return long
	 */
	public long getNStorageStatusID()
	{
		return nStorageStatusID;
	}

	/**
	 * Returns the queryBookCode.
	 * @return String
	 */
	public String getQueryBookCode()
	{
		return QueryBookCode;
	}

	/**
	 * Returns the sCodeEnd.
	 * @return String
	 */
	public String getSCodeEnd()
	{
		return sCodeEnd;
	}

	/**
	 * Returns the sCodeStart.
	 * @return String
	 */
	public String getSCodeStart()
	{
		return sCodeStart;
	}

	/**
	 * Returns the acceptorName.
	 * @return String
	 */
	public String getStrAcceptorName()
	{
		return strAcceptorName;
	}

	/**
	 * Returns the currentHolder.
	 * @return String
	 */
	public String getStrCurrentHolder()
	{
		return strCurrentHolder;
	}

	/**
	 * Sets the createEnd.
	 * @param createEnd The createEnd to set
	 */
	public void setCreateEnd(Timestamp createEnd)
	{
		dtCreateEnd = createEnd;
	}

	/**
	 * Sets the createStart.
	 * @param createStart The createStart to set
	 */
	public void setCreateStart(Timestamp createStart)
	{
		dtCreateStart = createStart;
	}

	/**
	 * Sets the endEnd.
	 * @param endEnd The endEnd to set
	 */
	public void setEndEnd(Timestamp endEnd)
	{
		dtEndEnd = endEnd;
	}

	/**
	 * Sets the endStart.
	 * @param endStart The endStart to set
	 */
	public void setEndStart(Timestamp endStart)
	{
		dtEndStart = endStart;
	}

	/**
	 * Sets the inDateEnd.
	 * @param inDateEnd The inDateEnd to set
	 */
	public void setInDateEnd(Timestamp inDateEnd)
	{
		dtInDateEnd = inDateEnd;
	}

	/**
	 * Sets the inDateStart.
	 * @param inDateStart The inDateStart to set
	 */
	public void setInDateStart(Timestamp inDateStart)
	{
		dtInDateStart = inDateStart;
	}

	/**
	 * Sets the inputDateEnd.
	 * @param inputDateEnd The inputDateEnd to set
	 */
	public void setInputDateEnd(Timestamp inputDateEnd)
	{
		dtInputDateEnd = inputDateEnd;
	}

	/**
	 * Sets the inputDateStart.
	 * @param inputDateStart The inputDateStart to set
	 */
	public void setInputDateStart(Timestamp inputDateStart)
	{
		dtInputDateStart = inputDateStart;
	}

	/**
	 * Sets the queryEnd.
	 * @param queryEnd The queryEnd to set
	 */
	public void setQueryEnd(Timestamp queryEnd)
	{
		dtQueryEnd = queryEnd;
	}

	/**
	 * Sets the queryStart.
	 * @param queryStart The queryStart to set
	 */
	public void setQueryStart(Timestamp queryStart)
	{
		dtQueryStart = queryStart;
	}

	/**
	 * Sets the billSoureID.
	 * @param billSoureID The billSoureID to set
	 */
	public void setlBillSoureID(long billSoureID)
	{
		lBillSoureID = billSoureID;
	}

	/**
	 * Sets the mAmounEnd.
	 * @param mAmounEnd The mAmounEnd to set
	 */
	public void setMAmounEnd(double mAmounEnd)
	{
		this.mAmounEnd = mAmounEnd;
	}

	/**
	 * Sets the mAmounStart.
	 * @param mAmounStart The mAmounStart to set
	 */
	public void setMAmounStart(double mAmounStart)
	{
		this.mAmounStart = mAmounStart;
	}

	/**
	 * Sets the nConsignStatusID.
	 * @param nConsignStatusID The nConsignStatusID to set
	 */
	public void setNConsignStatusID(long nConsignStatusID)
	{
		this.nConsignStatusID = nConsignStatusID;
	}

	/**
	 * Sets the nConsignTime.
	 * @param nConsignTime The nConsignTime to set
	 */
	public void setNConsignTime(long nConsignTime)
	{
		this.nConsignTime = nConsignTime;
	}

	/**
	 * Sets the nCurrencyID.
	 * @param nCurrencyID The nCurrencyID to set
	 */
	public void setNCurrencyID(long nCurrencyID)
	{
		this.nCurrencyID = nCurrencyID;
	}

	/**
	 * Sets the nDraftTypeID.
	 * @param nDraftTypeID The nDraftTypeID to set
	 */
	public void setNDraftTypeID(long nDraftTypeID)
	{
		this.nDraftTypeID = nDraftTypeID;
	}

	/**
	 * Sets the nInputUserID.
	 * @param nInputUserID The nInputUserID to set
	 */
	public void setNInputUserID(long nInputUserID)
	{
		this.nInputUserID = nInputUserID;
	}

	/**
	 * Sets the nModuleSourceID.
	 * @param nModuleSourceID The nModuleSourceID to set
	 */
	public void setNModuleSourceID(long nModuleSourceID)
	{
		this.nModuleSourceID = nModuleSourceID;
	}

	/**
	 * Sets the nOfficeID.
	 * @param nOfficeID The nOfficeID to set
	 */
	public void setNOfficeID(long nOfficeID)
	{
		this.nOfficeID = nOfficeID;
	}

	/**
	 * Sets the nQueryStatusID.
	 * @param nQueryStatusID The nQueryStatusID to set
	 */
	public void setNQueryStatusID(long nQueryStatusID)
	{
		this.nQueryStatusID = nQueryStatusID;
	}

	/**
	 * Sets the nStorageStatusID.
	 * @param nStorageStatusID The nStorageStatusID to set
	 */
	public void setNStorageStatusID(long nStorageStatusID)
	{
		this.nStorageStatusID = nStorageStatusID;
	}

	/**
	 * Sets the queryBookCode.
	 * @param queryBookCode The queryBookCode to set
	 */
	public void setQueryBookCode(String queryBookCode)
	{
		QueryBookCode = queryBookCode;
	}

	/**
	 * Sets the sCodeEnd.
	 * @param sCodeEnd The sCodeEnd to set
	 */
	public void setSCodeEnd(String sCodeEnd)
	{
		this.sCodeEnd = sCodeEnd;
	}

	/**
	 * Sets the sCodeStart.
	 * @param sCodeStart The sCodeStart to set
	 */
	public void setSCodeStart(String sCodeStart)
	{
		this.sCodeStart = sCodeStart;
	}

	/**
	 * Sets the acceptorName.
	 * @param acceptorName The acceptorName to set
	 */
	public void setStrAcceptorName(String acceptorName)
	{
		strAcceptorName = acceptorName;
	}

	/**
	 * Sets the currentHolder.
	 * @param currentHolder The currentHolder to set
	 */
	public void setStrCurrentHolder(String currentHolder)
	{
		strCurrentHolder = currentHolder;
	}

	/**
	 * @return Returns the dtCreateEnd.
	 */
	public Timestamp getDtCreateEnd() {
		return dtCreateEnd;
	}
	/**
	 * @return Returns the dtCreateStart.
	 */
	public Timestamp getDtCreateStart() {
		return dtCreateStart;
	}
	/**
	 * @return Returns the dtEndEnd.
	 */
	public Timestamp getDtEndEnd() {
		return dtEndEnd;
	}
	/**
	 * @return Returns the dtEndStart.
	 */
	public Timestamp getDtEndStart() {
		return dtEndStart;
	}
	/**
	 * @return Returns the dtInDateEnd.
	 */
	public Timestamp getDtInDateEnd() {
		return dtInDateEnd;
	}
	/**
	 * @return Returns the dtInDateStart.
	 */
	public Timestamp getDtInDateStart() {
		return dtInDateStart;
	}
	/**
	 * @return Returns the dtInputDateEnd.
	 */
	public Timestamp getDtInputDateEnd() {
		return dtInputDateEnd;
	}
	/**
	 * @return Returns the dtInputDateStart.
	 */
	public Timestamp getDtInputDateStart() {
		return dtInputDateStart;
	}
	/**
	 * @param dtCreateEnd The dtCreateEnd to set.
	 */
	public void setDtCreateEnd(Timestamp dtCreateEnd) {
		this.dtCreateEnd = dtCreateEnd;
	}
	/**
	 * @param dtCreateStart The dtCreateStart to set.
	 */
	public void setDtCreateStart(Timestamp dtCreateStart) {
		this.dtCreateStart = dtCreateStart;
	}
	/**
	 * @param dtEndEnd The dtEndEnd to set.
	 */
	public void setDtEndEnd(Timestamp dtEndEnd) {
		this.dtEndEnd = dtEndEnd;
	}
	/**
	 * @param dtEndStart The dtEndStart to set.
	 */
	public void setDtEndStart(Timestamp dtEndStart) {
		this.dtEndStart = dtEndStart;
	}
	/**
	 * @param dtInDateEnd The dtInDateEnd to set.
	 */
	public void setDtInDateEnd(Timestamp dtInDateEnd) {
		this.dtInDateEnd = dtInDateEnd;
	}
	/**
	 * @param dtInDateStart The dtInDateStart to set.
	 */
	public void setDtInDateStart(Timestamp dtInDateStart) {
		this.dtInDateStart = dtInDateStart;
	}
	/**
	 * @param dtInputDateEnd The dtInputDateEnd to set.
	 */
	public void setDtInputDateEnd(Timestamp dtInputDateEnd) {
		this.dtInputDateEnd = dtInputDateEnd;
	}
	/**
	 * @param dtInputDateStart The dtInputDateStart to set.
	 */
	public void setDtInputDateStart(Timestamp dtInputDateStart) {
		this.dtInputDateStart = dtInputDateStart;
	}
	
	/**
	 * @return Returns the desc.
	 */
	public long getDesc() {
		return Desc;
	}
	/**
	 * @return Returns the orderParam.
	 */
	public long getOrderParam() {
		return OrderParam;
	}
	/**
	 * @param desc The desc to set.
	 */
	public void setDesc(long desc) {
		this.Desc = desc;
	}
	/**
	 * @param orderParam The orderParam to set.
	 */
	public void setOrderParam(long orderParam) {
		this.OrderParam = orderParam;
	}
	
	
	/**
	 * @return Returns the lBillDestinationID.
	 */
	public long getLBillDestinationID() {
		return lBillDestinationID;
	}
	/**
	 * @param billDestinationID The lBillDestinationID to set.
	 */
	public void setLBillDestinationID(long billDestinationID) {
		lBillDestinationID = billDestinationID;
	}
	
	/**
	 * @return Returns the pageLineCount.
	 */
	public long getPageLineCount() {
		return pageLineCount;
	}
	/**
	 * @return Returns the pageNo.
	 */
	public long getPageNo() {
		return pageNo;
	}
	/**
	 * @param pageLineCount The pageLineCount to set.
	 */
	public void setPageLineCount(long pageLineCount) {
		this.pageLineCount = pageLineCount;
	}
	/**
	 * @param pageNo The pageNo to set.
	 */
	public void setPageNo(long pageNo) {
		this.pageNo = pageNo;
	}
	
	/**
	 * @return Returns the pageCount.
	 */
	public long getPageCount() {
		return pageCount;
	}
	/**
	 * @param pageCount The pageCount to set.
	 */
	public void setPageCount(long pageCount) {
		this.pageCount = pageCount;
	}
	
	/**
	 * @return Returns the agentBankID.
	 */
	public long getAgentBankID() {
		return AgentBankID;
	}
	/**
	 * @param agentBankID The agentBankID to set.
	 */
	public void setAgentBankID(long agentBankID) {
		AgentBankID = agentBankID;
	}
	
	/**
	 * @return Returns the dtConsignEnd.
	 */
	public Timestamp getDtConsignEnd() {
		return dtConsignEnd;
	}
	/**
	 * @return Returns the dtConsignStart.
	 */
	public Timestamp getDtConsignStart() {
		return dtConsignStart;
	}
	/**
	 * @param dtConsignEnd The dtConsignEnd to set.
	 */
	public void setDtConsignEnd(Timestamp dtConsignEnd) {
		this.dtConsignEnd = dtConsignEnd;
	}
	/**
	 * @param dtConsignStart The dtConsignStart to set.
	 */
	public void setDtConsignStart(Timestamp dtConsignStart) {
		this.dtConsignStart = dtConsignStart;
	}
}
