/* Generated by Together */

package com.iss.itreasury.bill.draft.dataentity;

import com.iss.itreasury.bill.util.BillDataEntity;
import com.iss.itreasury.system.approval.dataentity.InutParameterInfo;

import java.sql.Timestamp;
public class TransDraftInInfo extends BillDataEntity {
  //private long ID = -1;
  private long OfficeID = -1;
  private long CurrencyID= -1;
  private long TransTypeID= -1;
  private String TransCode= "";
  private long BillSoureID= -1;
  private long BillID= -1;
  private Timestamp InDate = null;
  private String CurrentHolder= "";
  private String FFormerOwner= "";
  private String FormerOwner= "";
  private String InContractCode= "";
  private String InPayFormCode= "";
  private long InOnWayDays= 0;
  private double  InRate=0.0;
  private double InInterest=0.0;
  private String Abstract= "";
  private long  InputUserID=-1;
  private Timestamp InputDate=null;
  private long ModifyUserID=-1;
  private Timestamp ModifyDate=null;
  private long StatusID=-1;
  //added by qhzhou 2007-09-19
  private InutParameterInfo inutParameterInfo;
  /**
   * @return the inutParameterInfo
   */
  public InutParameterInfo getInutParameterInfo() {
  	return inutParameterInfo;
  }
  /**
   * @param inutParameterInfo the inutParameterInfo to set
   */
  public void setInutParameterInfo(InutParameterInfo inutParameterInfo) {
  	this.inutParameterInfo = inutParameterInfo;
  }  
/**
 * @return Returns the abstract.
 */
public String getAbstract() {
	return Abstract;
}
/**
 * @param abstract1 The abstract to set.
 */
public void setAbstract(String abstract1) {
	Abstract = abstract1;
	putUsedField("Abstract", Abstract);
}
/**
 * @return Returns the billID.
 */
public long getBillID() {
	return BillID;
}
/**
 * @param billID The billID to set.
 */
public void setBillID(long billID) {
	BillID = billID;
	putUsedField("BillID", BillID);
}
/**
 * @return Returns the billSoureID.
 */
public long getBillSoureID() {
	return BillSoureID;
}
/**
 * @param billSoureID The billSoureID to set.
 */
public void setBillSoureID(long billSoureID) {
	BillSoureID = billSoureID;
	putUsedField("BillSoureID", BillSoureID);
}
/**
 * @return Returns the currencyID.
 */
public long getCurrencyID() {
	return CurrencyID;
}
/**
 * @param currencyID The currencyID to set.
 */
public void setCurrencyID(long currencyID) {
	CurrencyID = currencyID;
	putUsedField("CurrencyID", CurrencyID);
}
/**
 * @return Returns the currentHolder.
 */
public String getCurrentHolder() {
	return CurrentHolder;
}
/**
 * @param currentHolder The currentHolder to set.
 */
public void setCurrentHolder(String currentHolder) {
	CurrentHolder = currentHolder;
	putUsedField("CurrentHolder", CurrentHolder);
}
/**
 * @return Returns the fFormerOwner.
 */
public String getFFormerOwner() {
	return FFormerOwner;
}
/**
 * @param formerOwner The fFormerOwner to set.
 */
public void setFFormerOwner(String formerOwner) {
	FFormerOwner = formerOwner;
	putUsedField("FFormerOwner", FFormerOwner);
}
/**
 * @return Returns the formerOwner.
 */
public String getFormerOwner() {
	return FormerOwner;
}
/**
 * @param formerOwner The formerOwner to set.
 */
public void setFormerOwner(String formerOwner) {
	FormerOwner = formerOwner;
	putUsedField("FormerOwner", FormerOwner);
}
/**
 * @return Returns the inContractCode.
 */
public String getInContractCode() {
	return InContractCode;
}
/**
 * @param inContractCode The inContractCode to set.
 */
public void setInContractCode(String inContractCode) {
	InContractCode = inContractCode;
	putUsedField("InContractCode", InContractCode);
}
/**
 * @return Returns the inDate.
 */
public Timestamp getInDate() {
	return InDate;
}
/**
 * @param inDate The inDate to set.
 */
public void setInDate(Timestamp inDate) {
	InDate = inDate;
	putUsedField("InDate", InDate);
}
/**
 * @return Returns the inInterest.
 */
public double getInInterest() {
	return InInterest;
}
/**
 * @param inInterest The inInterest to set.
 */
public void setInInterest(double inInterest) {
	InInterest = inInterest;
	putUsedField("InInterest", InInterest);
}
/**
 * @return Returns the inOnWayDays.
 */
public long getInOnWayDays() {
	return InOnWayDays;
}
/**
 * @param inOnWayDays The inOnWayDays to set.
 */
public void setInOnWayDays(long inOnWayDays) {
	InOnWayDays = inOnWayDays;
	putUsedField("InOnWayDays", InOnWayDays);
}
/**
 * @return Returns the inPayFormCode.
 */
public String getInPayFormCode() {
	return InPayFormCode;
}
/**
 * @param inPayFormCode The inPayFormCode to set.
 */
public void setInPayFormCode(String inPayFormCode) {
	InPayFormCode = inPayFormCode;
	putUsedField("InPayFormCode", InPayFormCode);
}
/**
 * @return Returns the inputDate.
 */
public Timestamp getInputDate() {
	return InputDate;
}
/**
 * @param inputDate The inputDate to set.
 */
public void setInputDate(Timestamp inputDate) {
	InputDate = inputDate;
	putUsedField("InputDate", InputDate);
}
/**
 * @return Returns the inputUserID.
 */
public long getInputUserID() {
	return InputUserID;
}
/**
 * @param inputUserID The inputUserID to set.
 */
public void setInputUserID(long inputUserID) {
	InputUserID = inputUserID;
	putUsedField("InputUserID", InputUserID);
}
/**
 * @return Returns the inRate.
 */
public double getInRate() {
	return InRate;
}
/**
 * @param inRate The inRate to set.
 */
public void setInRate(double inRate) {
	InRate = inRate;
	putUsedField("InRate", InRate);
}
/**
 * @return Returns the modifyDate.
 */
public Timestamp getModifyDate() {
	return ModifyDate;
}
/**
 * @param modifyDate The modifyDate to set.
 */
public void setModifyDate(Timestamp modifyDate) {
	ModifyDate = modifyDate;
	putUsedField("ModifyDate", ModifyDate);
}
/**
 * @return Returns the modifyUserID.
 */
public long getModifyUserID() {
	return ModifyUserID;
}
/**
 * @param modifyUserID The modifyUserID to set.
 */
public void setModifyUserID(long modifyUserID) {
	ModifyUserID = modifyUserID;
	putUsedField("ModifyUserID", ModifyUserID);
}
/**
 * @return Returns the officeID.
 */
public long getOfficeID() {
	return OfficeID;
}
/**
 * @param officeID The officeID to set.
 */
public void setOfficeID(long officeID) {
	OfficeID = officeID;
	putUsedField("OfficeID", OfficeID);
}
/**
 * @return Returns the statusID.
 */
public long getStatusID() {
	return StatusID;
}
/**
 * @param statusID The statusID to set.
 */
public void setStatusID(long statusID) {
	StatusID = statusID;
	putUsedField("StatusID", StatusID);
}
/**
 * @return Returns the transCode.
 */
public String getTransCode() {
	return TransCode;
}
/**
 * @param transCode The transCode to set.
 */
public void setTransCode(String transCode) {
	TransCode = transCode;
	putUsedField("TransCode", TransCode);
}
/**
 * @return Returns the transTypeID.
 */
public long getTransTypeID() {
	return TransTypeID;
}
/**
 * @param transTypeID The transTypeID to set.
 */
public void setTransTypeID(long transTypeID) {
	TransTypeID = transTypeID;
	putUsedField("TransTypeID", TransTypeID);
}
}
