/* Generated by Together */

package com.iss.itreasury.bill.draft.dataentity;

import com.iss.itreasury.bill.util.BillDataEntity;
import java.sql.Timestamp;

/**
 * @author gqzhang 
 */
public class TransDraftConsignReplyInfo extends BillDataEntity {
    //private long ID	= -1;
private long OfficeID = -1;
private long CurrencyID = -1;	
private long TransTypeID = -1;	
private String TransCode = "";	
private long BillID 	= -1;	
private long ReplyStatusID 	= -1;	
private Timestamp AmountReceiveDate 	= null;	
private double AmountReceive = 0.0;	
private String RefuseReason 	= "";	
private String RefuseBookCode	="";
private String Abstract	="";
private long InputUserID = -1;
private Timestamp InputDate	= null;
private long ModifyUserID	= -1;
private Timestamp ModifyDate	= null;
private long StatusID	= -1;

/**
 * @return Returns the abstract.
 */
public String getAbstract() {
	return Abstract;
}
/**
 * @return Returns the amountReceive.
 */
public double getAmountReceive() {
	return AmountReceive;
}
/**
 * @return Returns the amountReceiveDate.
 */
public Timestamp getAmountReceiveDate() {
	return AmountReceiveDate;
}
/**
 * @return Returns the billID.
 */
public long getBillID() {
	return BillID;
}
/**
 * @return Returns the currencyID.
 */
public long getCurrencyID() {
	return CurrencyID;
}
/**
 * @return Returns the inputDate.
 */
public Timestamp getInputDate() {
	return InputDate;
}
/**
 * @return Returns the inputUserID.
 */
public long getInputUserID() {
	return InputUserID;
}
/**
 * @return Returns the modifyDate.
 */
public Timestamp getModifyDate() {
	return ModifyDate;
}
/**
 * @return Returns the modifyUserID.
 */
public long getModifyUserID() {
	return ModifyUserID;
}
	/**
	 * @return Returns the officeID.
	 */
	public long getOfficeID() {
		return OfficeID;
	}
/**
 * @return Returns the refuseBookCode.
 */
public String getRefuseBookCode() {
	return RefuseBookCode;
}
/**
 * @return Returns the refuseReason.
 */
public String getRefuseReason() {
	return RefuseReason;
}
/**
 * @return Returns the replyStatusID.
 */
public long getReplyStatusID() {
	return ReplyStatusID;
}
/**
 * @return Returns the statusID.
 */
public long getStatusID() {
	return StatusID;
}
/**
 * @return Returns the transCode.
 */
public String getTransCode() {
	return TransCode;
}
/**
 * @return Returns the transTypeID.
 */
public long getTransTypeID() {
	return TransTypeID;
}
/**
 * @param abstract1 The abstract to set.
 */
public void setAbstract(String abstract1) {
	Abstract = abstract1;
	putUsedField("Abstract", Abstract);
}
/**
 * @param amountReceive The amountReceive to set.
 */
public void setAmountReceive(double amountReceive) {
	AmountReceive = amountReceive;
	putUsedField("AmountReceive", AmountReceive);
}
/**
 * @param amountReceiveDate The amountReceiveDate to set.
 */
public void setAmountReceiveDate(Timestamp amountReceiveDate) {
	AmountReceiveDate = amountReceiveDate;
	putUsedField("AmountReceiveDate", AmountReceiveDate);
}
/**
 * @param billID The billID to set.
 */
public void setBillID(long billID) {
	BillID = billID;
	putUsedField("BillID", BillID);
}
/**
 * @param currencyID The currencyID to set.
 */
public void setCurrencyID(long currencyID) {
	CurrencyID = currencyID;
	putUsedField("CurrencyID", CurrencyID);
}
/**
 * @param inputDate The inputDate to set.
 */
public void setInputDate(Timestamp inputDate) {
	InputDate = inputDate;
	putUsedField("InputDate", InputDate);
}
/**
 * @param inputUserID The inputUserID to set.
 */
public void setInputUserID(long inputUserID) {
	InputUserID = inputUserID;
	putUsedField("InputUserID", InputUserID);
}
/**
 * @param modifyDate The modifyDate to set.
 */
public void setModifyDate(Timestamp modifyDate) {
	ModifyDate = modifyDate;
	putUsedField("ModifyDate", ModifyDate);
}
/**
 * @param modifyUserID The modifyUserID to set.
 */
public void setModifyUserID(long modifyUserID) {
	ModifyUserID = modifyUserID;
	putUsedField("ModifyUserID", ModifyUserID);
}
	/**
	 * @param officeID The officeID to set.
	 */
	public void setOfficeID(long officeID) {
		OfficeID = officeID;
		putUsedField("OfficeID", OfficeID);
	}
/**
 * @param refuseBookCode The refuseBookCode to set.
 */
public void setRefuseBookCode(String refuseBookCode) {
	RefuseBookCode = refuseBookCode;
	putUsedField("RefuseBookCode", RefuseBookCode);
}
/**
 * @param refuseReason The refuseReason to set.
 */
public void setRefuseReason(String refuseReason) {
	RefuseReason = refuseReason;
	putUsedField("RefuseReason", RefuseReason);
}
/**
 * @param replyStatusID The replyStatusID to set.
 */
public void setReplyStatusID(long replyStatusID) {
	ReplyStatusID = replyStatusID;
	putUsedField("ReplyStatusID", ReplyStatusID);
}
/**
 * @param statusID The statusID to set.
 */
public void setStatusID(long statusID) {
	StatusID = statusID;
	putUsedField("StatusID", StatusID);
}
/**
 * @param transCode The transCode to set.
 */
public void setTransCode(String transCode) {
	TransCode = transCode;
	putUsedField("TransCode", TransCode);
}
/**
 * @param transTypeID The transTypeID to set.
 */
public void setTransTypeID(long transTypeID) {
	TransTypeID = transTypeID;
	putUsedField("TransTypeID", TransTypeID);
}
}
