/* Generated by Together */

package com.iss.itreasury.bill.draft.dataentity;

import com.iss.itreasury.bill.util.BillDataEntity;
import com.iss.itreasury.system.approval.dataentity.InutParameterInfo;

import java.sql.Timestamp;
public class TransDraftOutInfo extends BillDataEntity {
	private long  OfficeID	 = -1;
	private long  CurrencyID = -1;	
	private long  TransTypeID = -1;	
	private String TransCode = "";	
	private long  BillDestinationID	= -1;
	private long  BillID	= -1;
	private Timestamp  OutDate  = null;	
	private String NextHolder  = "";	
	private String OutContractCode	 = "";
	private String OutPayFormCode	 = "";
	private long OutOnWayDays = 0;	
	private double OutRate	 = 0.0;
	private double OutInterest = 0.0;	
	private Timestamp  RepurchaseEndDate = null;	
	private double  SumRepurchaseInterest = 0.0;
	private String Abstract	 = "";
	private long TransDraftInID = -1;
	private long InputUserID = -1;	
	private Timestamp InputDate = null;	
	private long  ModifyUserID = -1;	
	private Timestamp ModifyDate  = null;	
	private long  StatusID	= -1;
	private long attachId = -1;		//¸½¼þ¹ØÁªID

	private InutParameterInfo inutParameterInfo;
	
	public long getAttachId() {
		return attachId;
	}
	public void setAttachId(long attachId) {
		this.attachId = attachId;
		putUsedField("attachId", attachId);
	}
	
	public InutParameterInfo getInutParameterInfo() {
		return inutParameterInfo;
	}
	/**
	 * @param inutParameterInfo the inutParameterInfo to set
	 */
	public void setInutParameterInfo(InutParameterInfo inutParameterInfo) {
		this.inutParameterInfo = inutParameterInfo;
	}
	/**
	 * @return Returns the abstract.
	 */
	public String getAbstract() {
		return Abstract;
	}
	/**
	 * @return Returns the billDestinationID.
	 */
	public long getBillDestinationID() {
		return BillDestinationID;
	}
	/**
	 * @return Returns the billID.
	 */
	public long getBillID() {
		return BillID;
	}
	/**
	 * @return Returns the currencyID.
	 */
	public long getCurrencyID() {
		return CurrencyID;
	}
	/**
	 * @return Returns the inputDate.
	 */
	public Timestamp getInputDate() {
		return InputDate;
	}
	/**
	 * @return Returns the inputUserID.
	 */
	public long getInputUserID() {
		return InputUserID;
	}
	/**
	 * @return Returns the modifyDate.
	 */
	public Timestamp getModifyDate() {
		return ModifyDate;
	}
	/**
	 * @return Returns the modifyUserID.
	 */
	public long getModifyUserID() {
		return ModifyUserID;
	}
	/**
	 * @return Returns the nextHolder.
	 */
	public String getNextHolder() {
		return NextHolder;
	}
	/**
	 * @return Returns the officeID.
	 */
	public long getOfficeID() {
		return OfficeID;
	}
	/**
	 * @return Returns the outContractCode.
	 */
	public String getOutContractCode() {
		return OutContractCode;
	}
	/**
	 * @return Returns the outDate.
	 */
	public Timestamp getOutDate() {
		return OutDate;
	}
	/**
	 * @return Returns the outInterest.
	 */
	public double getOutInterest() {
		return OutInterest;
	}
	/**
	 * @return Returns the outOnWayDays.
	 */
	public long getOutOnWayDays() {
		return OutOnWayDays;
	}
	/**
	 * @return Returns the outPayFormCode.
	 */
	public String getOutPayFormCode() {
		return OutPayFormCode;
	}
	/**
	 * @return Returns the outRate.
	 */
	public double getOutRate() {
		return OutRate;
	}
	/**
	 * @return Returns the repurchaseEndDate.
	 */
	public Timestamp getRepurchaseEndDate() {
		return RepurchaseEndDate;
	}
	/**
	 * @return Returns the statusID.
	 */
	public long getStatusID() {
		return StatusID;
	}
	/**
	 * @return Returns the sumRepurchaseInterest.
	 */
	public double getSumRepurchaseInterest() {
		return SumRepurchaseInterest;
	}
	/**
	 * @return Returns the transCode.
	 */
	public String getTransCode() {
		return TransCode;
	}
	/**
	 * @return Returns the transDraftInID.
	 */
	public long getTransDraftInID() {
		return TransDraftInID;
	}
	/**
	 * @return Returns the transTypeID.
	 */
	public long getTransTypeID() {
		return TransTypeID;
	}
	/**
	 * @param abstract1 The abstract to set.
	 */
	public void setAbstract(String abstract1) {
		Abstract = abstract1;
		putUsedField("Abstract",Abstract);
	}
	/**
	 * @param billDestinationID The billDestinationID to set.
	 */
	public void setBillDestinationID(long billDestinationID) {
		BillDestinationID = billDestinationID;
		putUsedField("BillDestinationID",BillDestinationID);
	}
	/**
	 * @param billID The billID to set.
	 */
	public void setBillID(long billID) {
		BillID = billID;
		putUsedField("BillID",BillID);
	}
	/**
	 * @param currencyID The currencyID to set.
	 */
	public void setCurrencyID(long currencyID) {
		CurrencyID = currencyID;
		putUsedField("CurrencyID",CurrencyID);
	}
	/**
	 * @param inputDate The inputDate to set.
	 */
	public void setInputDate(Timestamp inputDate) {
		InputDate = inputDate;
		putUsedField("InputDate",InputDate);
	}
	/**
	 * @param inputUserID The inputUserID to set.
	 */
	public void setInputUserID(long inputUserID) {
		InputUserID = inputUserID;
		putUsedField("InputUserID",InputUserID);
	}
	/**
	 * @param modifyDate The modifyDate to set.
	 */
	public void setModifyDate(Timestamp modifyDate) {
		ModifyDate = modifyDate;
		putUsedField("ModifyDate",ModifyDate);
	}
	/**
	 * @param modifyUserID The modifyUserID to set.
	 */
	public void setModifyUserID(long modifyUserID) {
		ModifyUserID = modifyUserID;
		putUsedField("ModifyUserID",ModifyUserID);
	}
	/**
	 * @param nextHolder The nextHolder to set.
	 */
	public void setNextHolder(String nextHolder) {
		NextHolder = nextHolder;
		putUsedField("NextHolder",NextHolder);
	}
	/**
	 * @param officeID The officeID to set.
	 */
	public void setOfficeID(long officeID) {
		OfficeID = officeID;
		putUsedField("OfficeID",OfficeID);
	}
	/**
	 * @param outContractCode The outContractCode to set.
	 */
	public void setOutContractCode(String outContractCode) {
		OutContractCode = outContractCode;
		putUsedField("OutContractCode",OutContractCode);
	}
	/**
	 * @param outDate The outDate to set.
	 */
	public void setOutDate(Timestamp outDate) {
		OutDate = outDate;
		putUsedField("OutDate",OutDate);
	}
	/**
	 * @param outInterest The outInterest to set.
	 */
	public void setOutInterest(double outInterest) {
		OutInterest = outInterest;
		putUsedField("OutInterest",OutInterest);
	}
	/**
	 * @param outOnWayDays The outOnWayDays to set.
	 */
	public void setOutOnWayDays(long outOnWayDays) {
		OutOnWayDays = outOnWayDays;
		putUsedField("OutOnWayDays",OutOnWayDays);
	}
	/**
	 * @param outPayFormCode The outPayFormCode to set.
	 */
	public void setOutPayFormCode(String outPayFormCode) {
		OutPayFormCode = outPayFormCode;
		putUsedField("OutPayFormCode",OutPayFormCode);
	}
	/**
	 * @param outRate The outRate to set.
	 */
	public void setOutRate(double outRate) {
		OutRate = outRate;
		putUsedField("OutRate",OutRate);
	}
	/**
	 * @param repurchaseEndDate The repurchaseEndDate to set.
	 */
	public void setRepurchaseEndDate(Timestamp repurchaseEndDate) {
		RepurchaseEndDate = repurchaseEndDate;
		putUsedField("RepurchaseEndDate",RepurchaseEndDate);
	}
	/**
	 * @param statusID The statusID to set.
	 */
	public void setStatusID(long statusID) {
		StatusID = statusID;
		putUsedField("StatusID",StatusID);
	}
	/**
	 * @param sumRepurchaseInterest The sumRepurchaseInterest to set.
	 */
	public void setSumRepurchaseInterest(double sumRepurchaseInterest) {
		SumRepurchaseInterest = sumRepurchaseInterest;
		putUsedField("SumRepurchaseInterest",SumRepurchaseInterest);
	}
	/**
	 * @param transCode The transCode to set.
	 */
	public void setTransCode(String transCode) {
		TransCode = transCode;
		putUsedField("TransCode",TransCode);
	}
	/**
	 * @param transDraftInID The transDraftInID to set.
	 */
	public void setTransDraftInID(long transDraftInID) {
		TransDraftInID = transDraftInID;
		putUsedField("TransDraftInID",TransDraftInID);
	}
	/**
	 * @param transTypeID The transTypeID to set.
	 */
	public void setTransTypeID(long transTypeID) {
		TransTypeID = transTypeID;
		putUsedField("TransTypeID",TransTypeID);
	}
}
