package com.iss.itreasury.loan.contract.bizlogic;
import java.rmi.RemoteException;
import javax.ejb.EJBObject;
import java.util.*;
import com.iss.itreasury.loan.contract.dataentity.*;
import com.iss.itreasury.util.*;
/**
 * Created 2003-8-15 14:50:59
 * Code generated by the Forte for Java EJB Module
 * @author yfan
 */
public interface Contract extends EJBObject
{

	/**
	 * 激活合同查找，区分合同管理人
	 * @Copyright (c) Jan. 2002, by iSoftStone Inc. All Rights Reserved
	 * @param lType        贷款种类，对应Notes中CODETYPE_LOANTYPE_CODE
	 * @param lCurrencyID 币种标识
	 * @param lOfficeID 办事处标识
	 * @param lUserID 登录人标识
	 * @param lContractIDFrom 合同编号起始
	 * @param lContractIDTo 合同编号结束
	 * @param lClientID 借款单位标识
	 * @param dAmountFrom 金额起始
	 * @param dAmountTo 金额结束
	 * @return Collection
	 * @exception Exception
	 */
	public Collection findContractByMultiOption(
		long lType,
		long lCurrencyID,
		long lOfficeID,
		long lUserID,
		long lContractIDFrom,
		long lContractIDTo,
		long lClientID,
		double dAmountFrom,
		double dAmountTo,
		long lPageLineCount,
		long lPageNo,
		long lOrderParam,
		long lDesc)
		throws RemoteException;

	/**
	 * 激活一个合同，操作ContractInfo表，将状态改为已激活
	 * <br>如果状态不是已复核，返回错误
	 * @param lContractID 合同标识
	 * @return 如果成功，返回1；如果状态不对，返回0
	 */
	public long activateContract(long lContractID) throws RemoteException, IRollbackException;

	/**
	 * 新增一个合同，操作loan_Contractform表
	 * @param Contractinfo oInfo 合同信息
	 * @return long 成功返回1 失败返回-1
	 * @writen by  2003-9-30
	 */
	public long add(ContractInfo oInfo) throws RemoteException;

	/**
	 * 查询合同信息，操作loan_Contractform表和它的附属表
	 * @param long lID 合同标示
	 * @return ContractInfo 
	 * @writen by  2003-10-6
	 */
	public ContractInfo findByID(long lID) throws RemoteException, IException;

	/**
	* 查询合同信息(修改)
	* Create Date: 2003-10-15
	* @param ContractQueryInfo 查询条件
	* @return Collection 
	* @exception Exception
	*/
	public Collection queryForUpdate(ContractQueryInfo qInfo) throws RemoteException, IException;

	/**
	 * 删除合同信息
	 * @param loanID
	 * @return
	 * @throws RemoteException
	 * @throws IException
	 */
	public long delete(long loanID) throws RemoteException, IException;

	/**
	* 查询合同信息(审核)
	* Create Date: 2003-10-15
	* @param ContractQueryInfo 查询条件
	* @return Collection
	* @exception Exception
	*/
	public Collection queryForExamine(ContractQueryInfo qInfo) throws RemoteException, IException;

	/**
	* 修改合同信息
	* Create Date: 2003-10-15
	* @param ContractInfo 合同信息
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long commit(ContractInfo info) throws RemoteException, IException;

	/**
	* 取消合同
	* Create Date: 2003-10-15
	* @param lID 合同ID
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long cancel(long lID) throws RemoteException, IException;

	/**
	* 审核通过
	* Create Date: 2003-10-15
	* @param lContractID 合同ID
	* @param strOpinion 审核意见
	* @param lUserID 登录人ID
	* @param  lNextUserID 下一级审核人
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long examinePass(long lContractID, String strOpinion, long lUserID, long lNextUserID,long lCurrencyID,long lOfficeID) throws RemoteException, IException;

	/**
	* 审核拒绝
	* Create Date: 2003-10-15
	* @param lContractID 合同ID
	* @param strOpinion 审核意见
	* @param lUserID 登录人ID
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long examineRefuse(long lContractID, String strOpinion, long lUserID,long lCurrencyID,long lOfficeID) throws RemoteException, IException;

	/**
	* 审核返回修正
	* Create Date: 2003-10-15
	* @param lContractID 合同ID
	* @param strOpinion 审核意见
	* @param lUserID 登录人ID
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long examineBack(long lContractID, String strOpinion, long lUserID,long lCurrencyID,long lOfficeID) throws RemoteException, IException;

	/**
	* 增加参与行信息
	* Create Date: 2003-10-15
	* @param Collection 银团信息 
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long addMember(Collection c) throws RemoteException, IException ;
	
	/**
	* 删除参与行信息
	* Create Date: 2003-10-15
	* @param Collection 银团信息
	* @return long 如大于0表示成功，小于等于0表示失败
	* @exception Exception
	*/
	public long delMember(Collection c) throws RemoteException, IException;
	
	public long commitAndApprovalInit(ContractInfo info) throws RemoteException, IRollbackException;
	
	public long doApproval(ContractInfo cInfo) throws RemoteException,IRollbackException;
	
	public long checkNextState(ContractInfo cInfo)throws RemoteException, IRollbackException;
	
	public long cancelApproval(ContractInfo cInfo)throws RemoteException, IRollbackException;
	
	/**
	 * 查询未放款金额(合同未做放款单金额)
	 * @param long lID 合同标示
	 * @return double 
	 * @writen by 2008-3-11
	 */
	public double findUnPayAmountByID(long lID,long payID) throws RemoteException, IException;
}
