/* Generated by Together */

package com.iss.itreasury.bill.blankvoucher.dataentity;

public class BlankExchangeInfo extends BlankTransDetailInfo {
	//数据库字段
	private long Id = -1;//
	private long BillTypeID = -1;//票据类型
	private long UseClientID = -1;//领用客户
	private long UseAccountID = -1;//领用帐号
	private long OldBillID = -1;//旧票据 id
	private long NewBillID = -1;//新票据 id
	
	//非数据库字段
	private long OfficeID = -1;
	private long CurrencyID = -1;
	private long UserID = -1;
	private String Summary = "";
	/**
	 * @return Returns the billTypeID.
	 */
	public long getBillTypeID()
	{
		return BillTypeID;
	}
	/**
	 * @param billTypeID The billTypeID to set.
	 */
	public void setBillTypeID(long billTypeID)
	{
		BillTypeID = billTypeID;
		putUsedField("billTypeID",BillTypeID);
	}
	/**
	 * @return Returns the id.
	 */
	public long getId()
	{
		return Id;
	}
	/**
	 * @param id The id to set.
	 */
	public void setId(long id)
	{
		Id = id;
		putUsedField("id",Id);
	}
	/**
	 * @return Returns the newBillID.
	 */
	public long getNewBillID()
	{
		return NewBillID;
	}
	/**
	 * @param newBillID The newBillID to set.
	 */
	public void setNewBillID(long newBillID)
	{
		NewBillID = newBillID;
		putUsedField("newBillID",NewBillID);
	}
	/**
	 * @return Returns the oldBillID.
	 */
	public long getOldBillID()
	{
		return OldBillID;
	}
	/**
	 * @param oldBillID The oldBillID to set.
	 */
	public void setOldBillID(long oldBillID)
	{
		OldBillID = oldBillID;
		putUsedField("oldBillID",OldBillID);
	}
	/**
	 * @return Returns the useAccountID.
	 */
	public long getUseAccountID()
	{
		return UseAccountID;
	}
	/**
	 * @param useAccountID The useAccountID to set.
	 */
	public void setUseAccountID(long useAccountID)
	{
		UseAccountID = useAccountID;
		putUsedField("useAccountID",UseAccountID);
	}
	/**
	 * @return Returns the useClientID.
	 */
	public long getUseClientID()
	{
		return UseClientID;
	}
	/**
	 * @param useClientID The useClientID to set.
	 */
	public void setUseClientID(long useClientID)
	{
		UseClientID = useClientID;
		putUsedField("useClientID",UseClientID);
	}
	/**
	 * @return Returns the currencyID.
	 */
	public long getCurrencyID()
	{
		return CurrencyID;
	}
	/**
	 * @param currencyID The currencyID to set.
	 */
	public void setCurrencyID(long currencyID)
	{
		CurrencyID = currencyID;
	}
	/**
	 * @return Returns the officeID.
	 */
	public long getOfficeID()
	{
		return OfficeID;
	}
	/**
	 * @param officeID The officeID to set.
	 */
	public void setOfficeID(long officeID)
	{
		OfficeID = officeID;
	}
	/**
	 * @return Returns the userID.
	 */
	public long getUserID()
	{
		return UserID;
	}
	/**
	 * @param userID The userID to set.
	 */
	public void setUserID(long userID)
	{
		UserID = userID;
	}
	/**
	 * @return Returns the summary.
	 */
	public String getSummary()
	{
		return Summary;
	}
	/**
	 * @param summary The summary to set.
	 */
	public void setSummary(String summary)
	{
		Summary = summary;
	}
}
