/* Generated by Together */

package com.iss.itreasury.budget.constitute.dataentity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;

import com.iss.itreasury.budget.dataentity.BudgetBaseDataEntity;
public class BudgetPlanInfo extends BudgetBaseDataEntity{
    private long clientID= -1;     //客户ID
    private String versionNo = "";   //版本号
    private long budgetSystemID = -1;  //预算体系ID 
    private String budgetSystemName = "";  //预算体系名称
	private long budgetPeriodID= -1;     //预算周期
	private String budgetPeriodName = "";	//预算周期名称
	private Timestamp constituteDate=null; //编制日期
	private Timestamp startDate=null;  //开始日期
	private Timestamp endDate=null;  //结束日期
    private String remark="";  //备注
	private long nextCheckUserID = -1;  //下一级审核人
	private long nextCheckLevel = -1;  //下一个审批级别
	private long isLowLevel = -1;  //审批流程
	private long budgetFlag= -1;     //预算标志 0 正常预算 1 调整预算 2 汇总预算
	private long statusID =-1;   //状态ID
	private long inputUserID =-1; //录入人
	private Timestamp inputDate=null; //录入日期
	private long updateUserID = -1; //修改人
	private Timestamp updateDate=null;  //修改日期
    private Collection planDetail = null; //预算明细
    private long officeID = -1;
    private long currencyID = -1;
    private long sumBudgetPlanID = -1;   //汇总预算ID(上级汇总)
    
    //查询编制时用的字段
    private long[] showColumn = null;	//显示哪些列 BUDGETConstant.BudgetColumnList类
	/**
	 * @return Returns the budgetFlag.
	 */
	public long getBudgetFlag() {
		return budgetFlag;
	}
	/**
	 * @param budgetFlag The budgetFlag to set.
	 */
	public void setBudgetFlag(long budgetFlag) {
		this.budgetFlag = budgetFlag;
		putUsedField("budgetFlag", budgetFlag);
	}
	/**
	 * @return Returns the budgetPeriod.
	 */
	public long getBudgetPeriodID() {
		return budgetPeriodID;
	}
	/**
	 * @param budgetPeriod The budgetPeriod to set.
	 */
	public void setBudgetPeriodID(long budgetPeriod) {
		this.budgetPeriodID = budgetPeriod;
		putUsedField("budgetPeriodID", budgetPeriodID);
	}
	/**
	 * @return Returns the budgetSystemID.
	 */
	public long getBudgetSystemID() {
		return budgetSystemID;
	}
	/**
	 * @param budgetSystemID The budgetSystemID to set.
	 */
	public void setBudgetSystemID(long budgetSystemID) {
		this.budgetSystemID = budgetSystemID;
		putUsedField("budgetSystemID", budgetSystemID);
	}
	/**
	 * @return Returns the clientID.
	 */
	public long getClientID() {
		return clientID;
	}
	/**
	 * @param clientID The clientID to set.
	 */
	public void setClientID(long clientID) {
		this.clientID = clientID;
		putUsedField("clientID", clientID);
	}
	/**
	 * @return Returns the constituteDate.
	 */
	public Timestamp getConstituteDate() {
		return constituteDate;
	}
	/**
	 * @param constituteDate The constituteDate to set.
	 */
	public void setConstituteDate(Timestamp constituteDate) {
		this.constituteDate = constituteDate;
		putUsedField("planDate", constituteDate);
	}
	/**
	 * @return Returns the endDate.
	 */
	public Timestamp getEndDate() {
		return endDate;
	}
	/**
	 * @param endDate The endDate to set.
	 */
	public void setEndDate(Timestamp endDate) {
		this.endDate = endDate;
		putUsedField("endDate", endDate);
	}
	/**
	 * @return Returns the inputDate.
	 */
	public Timestamp getInputDate() {
		return inputDate;
	}
	/**
	 * @param inputDate The inputDate to set.
	 */
	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
		putUsedField("inputDate", inputDate);
	}
	/**
	 * @return Returns the inputUserID.
	 */
	public long getInputUserID() {
		return inputUserID;
	}
	/**
	 * @param inputUserID The inputUserID to set.
	 */
	public void setInputUserID(long inputUserID) {
		this.inputUserID = inputUserID;
		putUsedField("inputUserID", inputUserID);
	}
	/**
	 * @return Returns the nextCheckUserID.
	 */
	public long getNextCheckUserID() {
		return nextCheckUserID;
	}
	/**
	 * @param nextCheckUserID The nextCheckUserID to set.
	 */
	public void setNextCheckUserID(long nextCheckUserID) {
		this.nextCheckUserID = nextCheckUserID;
		putUsedField("nextCheckUserID", nextCheckUserID);
	}
	/**
	 * @return Returns the planDetail.
	 */
	public Collection getPlanDetail() {
		return planDetail;
	}
	/**
	 * @param planDetail The planDetail to set.
	 */
	public void setPlanDetail(Collection planDetail) {
		this.planDetail = planDetail;
	}
	/**
	 * @return Returns the remark.
	 */
	public String getRemark() {
		return remark;
	}
	/**
	 * @param remark The remark to set.
	 */
	public void setRemark(String remark) {
		this.remark = remark;
		putUsedField("remark", remark);
	}
	/**
	 * @return Returns the startDate.
	 */
	public Timestamp getStartDate() {
		return startDate;
	}
	/**
	 * @param startDate The startDate to set.
	 */
	public void setStartDate(Timestamp startDate) {
		this.startDate = startDate;
		putUsedField("startDate", startDate);
	}
	/**
	 * @return Returns the statusID.
	 */
	public long getStatusID() {
		return statusID;
	}
	/**
	 * @param statusID The statusID to set.
	 */
	public void setStatusID(long statusID) {
		this.statusID = statusID;
		putUsedField("statusID", statusID);
	}
	/**
	 * @return Returns the updateDate.
	 */
	public Timestamp getUpdateDate() {
		return updateDate;
	}
	/**
	 * @param updateDate The updateDate to set.
	 */
	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
		putUsedField("updateDate", updateDate);
	}
	/**
	 * @return Returns the updateUserID.
	 */
	public long getUpdateUserID() {
		return updateUserID;
	}
	/**
	 * @param updateUserID The updateUserID to set.
	 */
	public void setUpdateUserID(long updateUserID) {
		this.updateUserID = updateUserID;
		putUsedField("updateUserID", updateUserID);
	}
	/**
	 * @return Returns the versionNo.
	 */
	public String getVersionNo() {
		return versionNo;
	}
	/**
	 * @param versionNo The versionNo to set.
	 */
	public void setVersionNo(String versionNo) {
		this.versionNo = versionNo;
		putUsedField("versionNo", versionNo);
	}

    /**
     * @return Returns the showColumn.
     */
    public long[] getShowColumn() {
        return showColumn;
    }
    /**
     * @param showColumn The showColumn to set.
     */
    public void setShowColumn(long[] showColumn) {
        this.showColumn = showColumn;
    }
    /**
     * @return Returns the budgetSystemName.
     */
    public String getBudgetSystemName() {
        return budgetSystemName;
    }
    /**
     * @param budgetSystemName The budgetSystemName to set.
     */
    public void setBudgetSystemName(String budgetSystemName) {
        this.budgetSystemName = budgetSystemName;
    }
    /**
     * @return Returns the budgetPeriodName.
     */
    public String getBudgetPeriodName() {
        return budgetPeriodName;
    }
    /**
     * @param budgetPeriodName The budgetPeriodName to set.
     */
    public void setBudgetPeriodName(String budgetPeriodName) {
        this.budgetPeriodName = budgetPeriodName;
    }
    /**
     * @return Returns the isLowLevel.
     */
    public long getIsLowLevel() {
        return isLowLevel;
    }
    /**
     * @param isLowLevel The isLowLevel to set.
     */
    public void setIsLowLevel(long isLowLevel) {
        this.isLowLevel = isLowLevel;
        putUsedField("isLowLevel", isLowLevel);
    }
    /**
     * @return Returns the nextCheckLevel.
     */
    public long getNextCheckLevel() {
        return nextCheckLevel;
    }
    /**
     * @param nextCheckLevel The nextCheckLevel to set.
     */
    public void setNextCheckLevel(long nextCheckLevel) {
        this.nextCheckLevel = nextCheckLevel;
        putUsedField("nextCheckLevel", nextCheckLevel);
    }
    
    /**
     * @return Returns the currencyID.
     */
    public long getCurrencyID() {
        return currencyID;
    }
    /**
     * @param currencyID The currencyID to set.
     */
    public void setCurrencyID(long currencyID) {
        this.currencyID = currencyID;
        putUsedField("currencyID", currencyID);
    }
    /**
     * @return Returns the officeID.
     */
    public long getOfficeID() {
        return officeID;
    }
    /**
     * @param officeID The officeID to set.
     */
    public void setOfficeID(long officeID) {
        this.officeID = officeID;
        putUsedField("officeID", officeID);
    }
	/**
	 * @return Returns the sumBudgetplanID.
	 */
	public long getSumBudgetplanID() {
		return sumBudgetPlanID;
	}
	/**
	 * @param sumBudgetplanID The sumBudgetplanID to set.
	 */
	public void setSumBudgetplanID(long sumBudgetPlanID) {
		this.sumBudgetPlanID = sumBudgetPlanID;
		putUsedField("sumBudgetPlanID", sumBudgetPlanID);
	}
}
