/* Generated by Together */

package com.iss.itreasury.budget.setting.dataentity;

import com.iss.itreasury.budget.dataentity.BudgetBaseDataEntity;
public class ParameterInfo extends BudgetBaseDataEntity{
    private long ebankLink=-1;     //预算属性 是否与网银挂接
    private long settmentLink=-1;       //是否与结算挂接
    private long budgetUnit = -1;     //	预算计量单位：如万元、千元，一般为元
    private long  budgetType  = -1;     //预算控制类型：刚性预算、柔性预算。此参数还可以在预算项目设置时进行进一步的项目级设置
    private long controlType=-1;       //	预算控制方式：总额控制、明细控制。此参数还可以在预算项目设置时进行进一步的项目级定义。
    private long caculateType = -1;    //	预算项目公式的计算方式
    private long nestingMaxLevel  =-1;         //公式嵌套层数
    private long changeMaxNum = -1;              //预算调整次数 
	/**
	 * @return Returns the budgetType.
	 */
	public long getBudgetType() {
		return budgetType;
		
	}
	/**
	 * @param budgetType The budgetType to set.
	 */
	public void setBudgetType(long budgetType) {
		this.budgetType = budgetType;
		putUsedField("budgetType", budgetType);
	}
	/**
	 * @return Returns the budgetUnit.
	 */
	public long getBudgetUnit() {
		return budgetUnit;
	}
	/**
	 * @param budgetUnit The budgetUnit to set.
	 */
	public void setBudgetUnit(long budgetUnit) {
		this.budgetUnit = budgetUnit;
		putUsedField("budgetUnit", budgetUnit);
	}
	/**
	 * @return Returns the caculateType.
	 */
	public long getCaculateType() {
		return caculateType;
	}
	/**
	 * @param caculateType The caculateType to set.
	 */
	public void setCaculateType(long caculateType) {
		this.caculateType = caculateType;
		putUsedField("caculateType", caculateType);
	}
	/**
	 * @return Returns the changeMaxNum.
	 */
	public long getChangeMaxNum() {
		return changeMaxNum;
	}
	/**
	 * @param changeMaxNum The changeMaxNum to set.
	 */
	public void setChangeMaxNum(long changeMaxNum) {
		this.changeMaxNum = changeMaxNum;
		putUsedField("changeMaxNum", changeMaxNum);
	}
	/**
	 * @return Returns the controlType.
	 */
	public long getControlType() {
		return controlType;
	}
	/**
	 * @param controlType The controlType to set.
	 */
	public void setControlType(long controlType) {
		this.controlType = controlType;
		putUsedField("controlType", controlType);
	}
/**
 * @return Returns the ebankLink.
 */
public long getEbankLink() {
	return ebankLink;
}
/**
 * @param ebankLink The ebankLink to set.
 */
public void setEbankLink(long ebankLink) {
	this.ebankLink = ebankLink;
	putUsedField("ebankLink", ebankLink);
}
	/**
	 * @return Returns the nestingMaxLevel.
	 */
	public long getNestingMaxLevel() {
		return nestingMaxLevel;
	}
	/**
	 * @param nestingMaxLevel The nestingMaxLevel to set.
	 */
	public void setNestingMaxLevel(long nestingMaxLevel) {
		this.nestingMaxLevel = nestingMaxLevel;
		putUsedField("nestingMaxLevel", nestingMaxLevel);
	}
	/**
	 * @return Returns the settlementLink.
	 */
	public long getSettmentLink() {
		return settmentLink;
	}
	/**
	 * @param settlementLink The settlementLink to set.
	 */
	public void setSettmentLink(long settmentLink) {
		this.settmentLink = settmentLink;
		putUsedField("settmentLink", settmentLink);
	}
}
