/* Generated by Together */

package com.iss.itreasury.clientmanage.bizdelegation;

import java.util.Collection;
import java.util.Vector;
import com.iss.itreasury.clientmanage.systemset.customfield.bizlogic.CustomFieldCmd;

public class CustomFieldDelegation {
	
	CustomFieldCmd cfc = new CustomFieldCmd();
	
	public Vector findByCondition(long StatusID, long officeID) throws Exception
	{
		Vector v = new Vector();
		try
		{				
			v = cfc.findByCondition(StatusID, officeID);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return (v);		
	}
	
	public Vector findByCondition(long StatusID, long officeID,long currencyID) throws Exception
	{
		Vector v = new Vector();
		try
		{				
			v = cfc.findByCondition(StatusID, officeID,currencyID);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return (v);		
	}
	
	
	public long save(Collection c) throws Exception
	{
		return cfc.save(c);
	}
	
//	public static void main(String[] args)
//	{
//		long lReturn = -1;
//		String[] name ={"gagr","hahta"};
//		String[] FieldID = {"36","37"};
//		long ID = 1;
//		long StatusID = 1;
//		Timestamp InputDate = null;
//		long InputUserID = 1;
//		try
//		{
//			CustomFieldDelegation cfd = new CustomFieldDelegation();
//			lReturn = cfd.save(FieldID,name,ID,InputDate,InputUserID,StatusID);
//			System.out.println(lReturn);
//		}
//		catch(Exception e)
//		{
//			e.printStackTrace();
//		}
//	}
}
