/* Generated by Together */

package com.iss.itreasury.bill.draft.dataentity.assemble;

import java.io.Serializable;
import java.util.Vector;
import com.iss.itreasury.bill.draft.dataentity.DiscountContractBillInfo;
import com.iss.itreasury.bill.draft.dataentity.TransDraftInInfo;
import com.iss.itreasury.bill.draft.dataentity.TransDraftOutInfo;

import com.iss.itreasury.system.approval.dataentity.InutParameterInfo;
public class DraftStorageAssembleInfo implements Serializable{
    private DiscountContractBillInfo discountContractBillInfo;
    private TransDraftInInfo transDraftInInfo;
    private TransDraftOutInfo transDraftOutInfo;
    
	/**
	 * @return Returns the discountContractBillInfo.
	 */
	public DiscountContractBillInfo getDiscountContractBillInfo() {
		return discountContractBillInfo;
	}
	/**
	 * @param discountContractBillInfo The discountContractBillInfo to set.
	 */
	public void setDiscountContractBillInfo(
			DiscountContractBillInfo discountContractBillInfo) {
		this.discountContractBillInfo = discountContractBillInfo;
	}
	/**
	 * @return Returns the transDraftInInfo.
	 */
	public TransDraftInInfo getTransDraftInInfo() {
		return transDraftInInfo;
	}
	/**
	 * @param transDraftInInfo The transDraftInInfo to set.
	 */
	public void setTransDraftInInfo(TransDraftInInfo transDraftInInfo) {
		this.transDraftInInfo = transDraftInInfo;
	}
	/**
	 * @return Returns the transDraftOutInfo.
	 */
	public TransDraftOutInfo getTransDraftOutInfo() {
		return transDraftOutInfo;
	}
	/**
	 * @param transDraftOutInfo The transDraftOutInfo to set.
	 */
	public void setTransDraftOutInfo(TransDraftOutInfo transDraftOutInfo) {
		this.transDraftOutInfo = transDraftOutInfo;
	}
}
