/* Generated by Together */

package com.iss.itreasury.budget.constitute.bizlogic;

/**
 * @author xrli
 *
 * To change the template for this generated type comment go to
 * Window>Preferences>Java>Code Generation>Code and Comments
 */
public interface BudgetConstituteHome extends javax.ejb.EJBHome
{
	BudgetConstitute create() throws javax.ejb.CreateException, java.rmi.RemoteException;
}
